Q(1, 1) = 1
Q(2, 1) = (F_trb*V_g*alpha_omg*c_1*omega_c**2 - 2*F_trb*alpha_omg*c_1* &
      omega_c**2)/(F_trb*V_g*alpha_gam*alpha_omg*c_1*omega_c**2 - F_trb &
      *lambda - alpha_omg*c_1*omega_c**2)
Q(3, 1) = 0
Q(4, 1) = 0
Q(5, 1) = 0
Q(6, 1) = 0
Q(1, 2) = 0
Q(2, 2) = -alpha_omg*c_1*omega_c**2/(F_trb*V_g*alpha_gam*alpha_omg*c_1* &
      omega_c**2 - F_trb*lambda - alpha_omg*c_1*omega_c**2)
Q(3, 2) = 0
Q(4, 2) = 0
Q(5, 2) = 0
Q(6, 2) = 0
Q(1, 3) = 0
Q(2, 3) = F_trb*alpha_grv*lambda/(F_trb*V_g*alpha_gam*alpha_omg*c_1* &
      omega_c**2 - F_trb*lambda - alpha_omg*c_1*omega_c**2)
Q(3, 3) = 1
Q(4, 3) = 0
Q(5, 3) = 0
Q(6, 3) = 0
Q(1, 4) = 0
Q(2, 4) = 0
Q(3, 4) = 0
Q(4, 4) = 1
Q(5, 4) = 0
Q(6, 4) = 0
Q(1, 5) = 0
Q(2, 5) = F_trb*alpha_omg*c_1*omega_c**2*ups_T/(F_trb*V_g*alpha_gam* &
      alpha_omg*c_1*omega_c**2 - F_trb*lambda - alpha_omg*c_1*omega_c** &
      2)
Q(3, 5) = 0
Q(4, 5) = 0
Q(5, 5) = 1
Q(6, 5) = 0
Q(1, 6) = 0
Q(2, 6) = 0
Q(3, 6) = 0
Q(4, 6) = 0
Q(5, 6) = 0
Q(6, 6) = 1
