Q(1, 1) = -F_trb*(V_g - 2)/(F_trb*(-V_g*alpha_gam + lambda/(alpha_omg* &
      c_1*omega_c**2)) + 1)
Q(1, 2) = -F_trb*(-V_g*alpha_gam + lambda/(alpha_omg*c_1*omega_c**2))/( &
      F_trb*(-V_g*alpha_gam + lambda/(alpha_omg*c_1*omega_c**2)) + 1)
Q(1, 3) = -F_trb*alpha_grv*lambda/(alpha_omg*c_1*omega_c**2*(F_trb*(-V_g &
      *alpha_gam + lambda/(alpha_omg*c_1*omega_c**2)) + 1))
Q(1, 4) = 0
Q(1, 5) = -F_trb*ups_T/(F_trb*(-V_g*alpha_gam + lambda/(alpha_omg*c_1* &
      omega_c**2)) + 1)
Q(1, 6) = 0
