# File     : Makefile
# Purpose  : makefile for src/interp subdir

# Variables

TARGETS=test_interp

# Flags

HDF5=yes

LDFLAGS=`mesasdk_hdf5_link`

# Include other makefiles

SUBDIRS=../extern/core:../common

include ../build/Make.inc

