! Module  : nad_bvp_m
! Purpose : nonadiabatic boundary value problem solver
!
! Copyright 2013-2026 Rich Townsend & The GYRE Team
!
! This file is part of GYRE. GYRE is free software: you can
! redistribute it and/or modify it under the terms of the GNU General
! Public License as published by the Free Software Foundation, version 3.
!
! GYRE is distributed in the hope that it will be useful, but WITHOUT
! ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
! or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
! License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.

#:include 'gyre.inc'

module nad_bvp_m

   ! Uses

   use forum_m, only: RD

   use bvp_m
   use context_m
   use grid_m
   use mode_m
   use mode_par_m
   use num_par_m
   use orbit_par_m
   use osc_par_m
   use point_m
   use resp_m
   use state_m
   use sysmtx_m
   use trans_m
   use wave_m

   use ISO_FORTRAN_ENV

   ! No implicit typing

   implicit none (type, external)

   ! Derived-type definitions

   type, extends(bvp_ct) :: nad_bvp_t
      private
      type(context_t), pointer     :: cx => null()
      class(trans_ct), allocatable :: tr(:)
      type(grid_t)                 :: gr
      type(mode_par_t)             :: md_p
      type(num_par_t)              :: nm_p
      type(osc_par_t)              :: os_p
   end type nad_bvp_t

   ! Interfaces

   interface nad_bvp_t
      module procedure nad_bvp_t_
   end interface nad_bvp_t

   interface mode_t
      module procedure mode_t_
   end interface mode_t

   interface resp_t
      module procedure resp_t_
   end interface resp_t

   ! Access specifiers

   public :: nad_bvp_t
   public :: mode_t
   public :: resp_t

   ! Default access

   private

contains

   function nad_bvp_t_(cx, gr, md_p, nm_p, os_p) result(bp)

      use bound_block_m
      use inter_block_m
      use inter_element_m
      use match_block_m
      use match_conds_m
      use nad_factory_m
      use nad_diff_block_m

      class(context_t), pointer, intent(in) :: cx
      type(grid_t), intent(in)              :: gr
      type(mode_par_t), intent(in)          :: md_p
      type(num_par_t), intent(in)           :: nm_p
      type(osc_par_t), intent(in)           :: os_p
      type(nad_bvp_t)                       :: bp

      class(bound_block_ct), allocatable  :: bb_i
      class(bound_block_ct), allocatable  :: bb_o
      integer                             :: j
      type(inter_element_ct), allocatable :: ie(:)
      class(match_conds_ct), allocatable  :: mc(:)

      ! Construct the nad_bvp type

      ! Initialize the boundary condition blocks

      bb_i = bound_block_ct(nad_ibound_conds_t(cx, os_p))
      bb_o = bound_block_ct(nad_obound_conds_t(cx, os_p))

      ! Initialize the intermediate blocks

      allocate(ie(gr%n-1))

      !$OMP PARALLEL DO
      do j = 1, gr%n-1

         associate( &
            pt_a => gr%pt(j), &
            pt_b => gr%pt(j+1))

            if (pt_a%s == pt_b%s) then
               allocate(ie(j)%ib, SOURCE=nad_diff_block_t(diff_eqns_factory_, cx, pt_a, pt_b, nm_p, os_p))
            else
               #:if defined('GFORTRAN_PR125610')
               mc = nad_match_conds_t_1_(cx, [pt_a,pt_b], os_p)
               #:else
               mc = nad_match_conds_t(cx, [pt_a,pt_b], os_p)
               #:endif
               allocate(ie(j)%ib, SOURCE=match_block_ct(mc))
            end if

         end associate

      end do

      ! Initialize the bvp_ct

      bp%bvp_ct = bvp_ct(bb_i, bb_o, ie, nm_p)

      ! Other initializations

      bp%cx => cx
      bp%gr = gr

      #:if defined('GFORTRAN_PR125610')
      bp%tr = nad_trans_t_1_(cx, gr%pt, os_p)
      #:else
      bp%tr = nad_trans_t(cx, gr%pt, os_p)
      #:endif

      bp%md_p = md_p
      bp%nm_p = nm_p
      bp%os_p = os_p

      ! Finish

      return

   contains

      subroutine diff_eqns_factory_(pt, de)

         use diff_eqns_m

         type(point_t), intent(in)                     :: pt(:)
         class(diff_eqns_ct), allocatable, intent(out) :: de(:)

         ! Initialize the differential equations

         #:if defined('GFORTRAN_PR125610')
         de = nad_diff_eqns_t_1_(cx, pt, os_p)
         #:else
         de = nad_diff_eqns_t(cx, pt, os_p)
         #:endif

         ! Finish

         return

      end subroutine diff_eqns_factory_

   end function nad_bvp_t_

   !****

   function mode_t_(bp, sm, st, id, chi, n_iter) result(md)

      class(nad_bvp_t), intent(in)    :: bp
      class(sysmtx_ct), intent(inout) :: sm
      type(state_ct), intent(in)      :: st
      integer, intent(in)             :: id
      real(RD), intent(in)            :: chi
      integer, intent(in)             :: n_iter
      type(mode_t)                    :: md

      complex(RD)  :: y(6,bp%n)
      integer      :: j
      type(wave_t) :: wv

      ! Calculate the homogeneous solution vector

      call bp%solve_hom(sm, st, y)

      !$OMP PARALLEL DO
      do j = 1, bp%n
         call bp%tr(j)%transform(st, y(:,j))
      end do

      ! Construct the mode_t

      wv = wave_t(st, y, bp%cx, bp%gr, bp%md_p, bp%nm_p, bp%os_p, id, chi, n_iter)

      md = mode_t(wv)

      ! Finish

      return

   end function mode_t_

   !****

   function resp_t_(bp, sm, st, id, or_p, k) result(rs)

      class(nad_bvp_t), intent(in)    :: bp
      class(sysmtx_ct), intent(inout) :: sm
      type(state_ct), intent(in)      :: st
      integer, intent(in)             :: id
      type(orbit_par_t)               :: or_p
      integer, intent(in)             :: k
      type(resp_t)                    :: rs

      complex(RD)  :: y(6,bp%n)
      integer      :: j
      type(wave_t) :: wv

      ! Calculate the inhomogeneous solution vector

      call bp%solve_inhom(sm, st, y)

      !$OMP PARALLEL DO
      do j = 1, bp%n
         call bp%tr(j)%transform(st, y(:,j))
      end do

      ! Construct the resp_t

      wv = wave_t(st, y, bp%cx, bp%gr, bp%md_p, bp%nm_p, bp%os_p, id, 0._RD, 1)

      rs = resp_t(wv, or_p, k)

      ! Finish

      return

   end function resp_t_

end module nad_bvp_m
