! Module  : nad_diff_block_m
! Purpose : nonadiabatic differential equations block
!
! Copyright 2013-2026 Rich Townsend & The GYRE Team
!
! This file is part of GYRE. GYRE is free software: you can
! redistribute it and/or modify it under the terms of the GNU General
! Public License as published by the Free Software Foundation, version 3.
!
! GYRE is distributed in the hope that it will be useful, but WITHOUT
! ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
! or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
! License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.

#:include 'gyre.inc'

module nad_diff_block_m

   ! Uses

   use forum_m, only: RD

   use context_m
   use diff_block_m
   use diff_eqns_m
   use ext_m
   use math_m
   use num_par_m
   use osc_par_m
   use point_m
   use state_m

   use ISO_FORTRAN_ENV

   ! No implicit typing

   implicit none (type, external)

   ! Derived-type definitions

   type, extends (diff_block_ct) :: nad_diff_block_t
      private
      type(context_t), pointer          :: cx => null()
      class(diff_block_ct), allocatable :: db
      class(diff_eqns_ct), allocatable  :: de
      real(RD)                          :: dx
   contains
      private
      procedure, public :: eval
   end type nad_diff_block_t

   ! Interfaces

   interface nad_diff_block_t
      module procedure nad_diff_block_t_
   end interface nad_diff_block_t

   ! Access specifiers

   public :: nad_diff_block_t

   ! Default access

   private

contains

   function nad_diff_block_t_(diff_eqns_factory, cx, pt_a, pt_b, nm_p, os_p) result(db)

      use diff_block_factory_m
      use nad_factory_m
      use trapz_block_m

      interface
         subroutine diff_eqns_factory(pt, de)
            use diff_eqns_m
            use point_m
            implicit none (type, external)
            type(point_t), intent(in)                     :: pt(:)
            class(diff_eqns_ct), allocatable, intent(out) :: de(:)
         end subroutine diff_eqns_factory
      end interface
      type(context_t), pointer, intent(in) :: cx
      type(point_t), intent(in)            :: pt_a
      type(point_t), intent(in)            :: pt_b
      type(num_par_t), intent(in)          :: nm_p
      type(osc_par_t), intent(in)          :: os_p
      type(nad_diff_block_t)               :: db

      type(point_t) :: pt_m

      ! Construct the nad_diff_block type

      db%cx => cx

      select case (nm_p%diff_scheme)
      case ('TRAPZ')
         allocate(db%db, SOURCE=trapz_block_ct(diff_eqns_factory, pt_a, pt_b, &
            [0.5_RD,0.5_RD,0.5_RD,0.5_RD,0._RD,1._RD]))
      case default
         allocate(db%db, SOURCE=diff_block_ct(diff_eqns_factory, pt_a, pt_b, nm_p))
      end select

      ! Set up midpoint diff_eqns_t (used for regularization of Magnus
      ! schemes)

      db%dx = pt_b%x - pt_a%x

      pt_m%s = pt_a%s
      pt_m%x = pt_a%x + 0.5_RD*db%dx

      db%de = nad_diff_eqns_t(cx, pt_m, os_p)

      db%n_e = db%db%n_e

      ! Finish

      return

   end function nad_diff_block_t_

   !****

   subroutine eval(this, st, E, scl, F, trans)

      use magnus_gl2_block_m
      use magnus_gl4_block_m
      use magnus_gl6_block_m

      class(nad_diff_block_t), intent(in)            :: this
      class(state_ct), intent(in)                    :: st
      complex(RD), contiguous, intent(out)           :: E(:,:)
      type(ext_ct), intent(out)                      :: scl
      complex(RD), contiguous, intent(out), optional :: F(:)
      logical, intent(in), optional                  :: trans

      logical, parameter :: MAGNUS_EIGVAL_MASK(3) = [.FALSE.,.FALSE.,.TRUE.]

      logical     :: regularize
      complex(RD) :: A(this%n_e,this%n_e)
      complex(RD) :: lambda(3)

      ! Evaluate the differential equations block

      call this%db%eval(st, E, scl, F, trans)

      ! Apply regularization corrections

      select type (db => this%db)
      class is (magnus_gl2_block_ct)
         regularize = .TRUE.
      class is (magnus_gl4_block_ct)
         regularize = .TRUE.
      class is (magnus_gl6_block_ct)
         regularize = .TRUE.
      class default
         regularize = .FALSE.
      end select

      if (regularize) then

         ! Rescale by the uncoupled eigenvalues, in order to help the root
         ! finder

         call this%de%eval(st, this%dx, A)

         lambda(1) = sqrt(A(2,1)*A(1,2))
         lambda(2) = sqrt(A(4,3)*A(3,4))
         lambda(3) = sqrt(A(6,5)*A(5,6))

         scl = scl*exp(ext_ct(-SUM(lambda, MASK=MAGNUS_EIGVAL_MASK)))

      end if

      ! Finish

      return

   end subroutine eval

end module nad_diff_block_m
