! Module  : ad_bvp_m
! Purpose : adiabatic bounary value problem solver
!
! Copyright 2013-2026 Rich Townsend & The GYRE Team
!
! This file is part of GYRE. GYRE is free software: you can
! redistribute it and/or modify it under the terms of the GNU General
! Public License as published by the Free Software Foundation, version 3.
!
! GYRE is distributed in the hope that it will be useful, but WITHOUT
! ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
! or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
! License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.

#:include 'gyre.inc'

module ad_bvp_m

   ! Uses

   use forum_m, only: RD

   use bvp_m
   use context_m
   use grid_m
   use mode_m
   use mode_par_m
   use model_m
   use num_par_m
   use osc_par_m
   use point_m
   use qad_eval_m
   use state_m
   use sysmtx_m
   use trans_m
   use wave_m

   use ISO_FORTRAN_ENV

   ! No implicit typing

   implicit none (type, external)

   ! Derived-type definitions

   type, extends(bvp_rt) :: ad_bvp_t
      private
      type(context_t), pointer     :: cx => null()
      class(trans_rt), allocatable :: tr(:)
      type(grid_t)                 :: gr
      type(qad_eval_t)             :: qe
      type(mode_par_t)             :: md_p
      type(num_par_t)              :: nm_p
      type(osc_par_t)              :: os_p
   end type ad_bvp_t

   ! Interfaces

   interface ad_bvp_t
      module procedure ad_bvp_t_
   end interface ad_bvp_t

   interface mode_t
      module procedure mode_t_
   end interface mode_t

   ! Access specifiers

   public :: ad_bvp_t
   public :: mode_t

   ! Default access

   private

contains

   function ad_bvp_t_(cx, gr, md_p, nm_p, os_p) result(bp)

      use ad_factory_m
      use bound_conds_m

      type(context_t), pointer, intent(in) :: cx
      type(grid_t), intent(in)             :: gr
      type(mode_par_t), intent(in)         :: md_p
      type(num_par_t), intent(in)          :: nm_p
      type(osc_par_t), intent(in)          :: os_p
      type(ad_bvp_t)                       :: bp

      class(bound_conds_rt), allocatable :: bc_i
      class(bound_conds_rt), allocatable :: bc_o

      ! Construct the ad_bvp type

      ! Initialize the base type

      bc_i = ad_ibound_conds_t(cx, os_p)
      bc_o = ad_obound_conds_t(cx, os_p)

      bp%bvp_rt = bvp_rt(gr, bc_i, bc_o, diff_eqns_factory_, match_conds_factory_, nm_p)

      ! Other initializations

      bp%cx => cx
      bp%gr = gr

      #:if defined('GFORTRAN_PR125610')
      bp%tr = ad_trans_t_1_(cx, gr%pt, os_p)
      #:else
      bp%tr = ad_trans_t(cx, gr%pt, os_p)
      #:endif

      if (os_p%quasiad_eigfuncs) then
         bp%qe = qad_eval_t(cx, gr, os_p)
      endif

      bp%md_p = md_p
      bp%nm_p = nm_p
      bp%os_p = os_p

      ! Finish

      return

   contains

      subroutine diff_eqns_factory_(pt, de)

         use diff_eqns_m

         type(point_t), intent(in)                     :: pt(:)
         class(diff_eqns_rt), allocatable, intent(out) :: de(:)

         ! Initialize the differential equations

         #:if defined('GFORTRAN_PR125610')
         de = ad_diff_eqns_t_1_(cx, pt, os_p)
         #:else
         de = ad_diff_eqns_t(cx, pt, os_p)
         #:endif

         ! Finish

         return

      end subroutine diff_eqns_factory_

      !****

      subroutine match_conds_factory_(pt, mc)

         use match_conds_m

         type(point_t), intent(in)                       :: pt(:)
         class(match_conds_rt), allocatable, intent(out) :: mc(:)

         ! Initialize the match conditions

         #:if defined('GFORTRAN_PR125610')
         mc = ad_match_conds_t_1_(cx, pt, os_p)
         #:else
         mc = ad_match_conds_t(cx, pt, os_p)
         #:endif

         ! Finish

         return

      end subroutine match_conds_factory_

   end function ad_bvp_t_

   !****

   function mode_t_(bp, sm, st, id, chi, n_iter) result(md)

      class(ad_bvp_t), intent(in)     :: bp
      class(sysmtx_rt), intent(inout) :: sm
      type(state_rt), intent(in)      :: st
      integer, intent(in)             :: id
      real(RD), intent(in)            :: chi
      integer, intent(in)             :: n_iter
      type(mode_t)                    :: md

      real(RD)       :: y(4,bp%n)
      integer        :: j
      type(state_ct) :: st_c
      complex(RD)    :: y_c(6,bp%n)
      type(wave_t)   :: wv

      ! Calculate the homogeneous solution vector

      call bp%solve_hom(sm, st, y)

      ! Convert to canonical form

      !$OMP PARALLEL DO
      do j = 1, bp%n
         call bp%tr(j)%transform(st, y(:,j))
      end do

      ! Set up complex eigenfunctions

      st_c = state_ct(CMPLX(st%omega, KIND=RD), st%omega)

      if (bp%os_p%quasiad_eigfuncs) then

         y_c = bp%qe%y_qad(st_c, y)

      else

         y_c(1:4,:) = y
         y_c(5:6,:) = 0._RD

      endif

      ! Construct the mode type

      wv = wave_t(st_c, y_c, bp%cx, bp%gr, bp%md_p, bp%nm_p, bp%os_p, id, chi, n_iter)

      md = mode_t(wv)

      ! Finish

      return

   end function mode_t_

end module ad_bvp_m
