! Module  : ad_factory_m
! Purpose : factory methods for adiabatic routines
!
! Copyright 2013-2026 Rich Townsend & The GYRE Team
!
! This file is part of GYRE. GYRE is free software: you can
! redistribute it and/or modify it under the terms of the GNU General
! Public License as published by the Free Software Foundation, version 3.
!
! GYRE is distributed in the hope that it will be useful, but WITHOUT
! ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
! or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
! License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.

#:include 'gyre.inc'

module ad_factory_m

   ! Uses

   use forum_m, only: RD

   use context_m
   use osc_par_m
   use point_m

   use ISO_FORTRAN_ENV

   ! No implicit typing

   implicit none (type, external)

   ! Interfaces

   interface ad_diff_eqns_t
      module procedure ad_diff_eqns_t_0_
      module procedure ad_diff_eqns_t_1_
   end interface ad_diff_eqns_t

   interface ad_match_conds_t
      module procedure ad_match_conds_t_0_
      module procedure ad_match_conds_t_1_
   end interface ad_match_conds_t

   interface ad_trans_t
      module procedure ad_trans_t_0_
      module procedure ad_trans_t_1_
   end interface ad_trans_t

   ! Access specifiers

   public :: ad_diff_eqns_t
   public :: ad_match_conds_t
   public :: ad_trans_t
   public :: ad_ibound_conds_t
   public :: ad_obound_conds_t
   #:if defined('GFORTRAN_PR125610')
   public :: ad_diff_eqns_t_0_
   public :: ad_diff_eqns_t_1_
   public :: ad_match_conds_t_0_
   public :: ad_match_conds_t_1_
   public :: ad_trans_t_0_
   public :: ad_trans_t_1_
   #:endif

   ! Default access

   private

contains

   #:for R in (0, 1)

      function ad_diff_eqns_t_${R}$_(cx, pt, os_p) result(de)

         use diff_eqns_m

         use gyre_ad_diff_eqns_m
         use dziem_ad_diff_eqns_m
         use jcd_ad_diff_eqns_m
         use rjcd_ad_diff_eqns_m
         use mix_ad_diff_eqns_m
         use lagp_ad_diff_eqns_m

         type(context_t), pointer, intent(in) :: cx
         type(point_t), intent(in)            :: pt${ARRAY_SPEC(R)}$
         type(osc_par_t), intent(in)          :: os_p
         class(diff_eqns_rt), allocatable     :: de${ARRAY_SPEC(R)}$

         ! Construct the ad_diff_eqns type

         select case(os_p%variables_set)
         case('GYRE')
            de = gyre_ad_diff_eqns_t(cx, pt)
         case('DZIEM')
            de = dziem_ad_diff_eqns_t(cx, pt)
         case('JCD')
            if (cx%l == 0) then
               de = rjcd_ad_diff_eqns_t(cx, pt)
            else
               de = jcd_ad_diff_eqns_t(cx, pt)
            end if
         case('MIX')
            de = mix_ad_diff_eqns_t(cx, pt)
         case('LAGP')
            de = lagp_ad_diff_eqns_t(cx, pt)
         case default
            @:ABORT('invalid variables_set')
         end select

         ! Finish

         return

      end function ad_diff_eqns_t_${R}$_

      !****

      function ad_match_conds_t_${R}$_(cx, pt, os_p) result(mc)

         use match_conds_m

         use gyre_ad_match_conds_m
         use dziem_ad_match_conds_m
         use jcd_ad_match_conds_m
         use rjcd_ad_match_conds_m
         use mix_ad_match_conds_m
         use lagp_ad_match_conds_m

         type(context_t), pointer, intent(in) :: cx
         type(point_t), intent(in)            :: pt${ARRAY_SPEC(R)}$
         type(osc_par_t), intent(in)          :: os_p
         class(match_conds_rt), allocatable   :: mc${ARRAY_SPEC(R)}$

         ! Construct the ad_match_conds

         select case(os_p%variables_set)
         case('GYRE')
            mc = gyre_ad_match_conds_t(cx, pt)
         case('DZIEM')
            mc = dziem_ad_match_conds_t(cx, pt)
         case('JCD')
            if (cx%l == 0) then
               mc = rjcd_ad_match_conds_t(cx, pt)
            else
               mc = jcd_ad_match_conds_t(cx, pt)
            end if
         case('MIX')
            mc = mix_ad_match_conds_t(cx, pt)
         case('LAGP')
            mc = lagp_ad_match_conds_t(cx, pt)
         case default
            @:ABORT('invalid variables_set')
         end select

         ! Finish

         return

      end function ad_match_conds_t_${R}$_

      !****

      function ad_trans_t_${R}$_(cx, pt, os_p) result(tr)

         use trans_m

         use gyre_ad_trans_m
         use dziem_ad_trans_m
         use jcd_ad_trans_m
         use rjcd_ad_trans_m
         use mix_ad_trans_m
         use lagp_ad_trans_m

         type(context_t), pointer, intent(in) :: cx
         type(point_t), intent(in)            :: pt${ARRAY_SPEC(R)}$
         type(osc_par_t), intent(in)          :: os_p
         class(trans_rt), allocatable         :: tr${ARRAY_SPEC(R)}$

         ! Construct the ad_trans type

         select case(os_p%variables_set)
         case('GYRE')
            tr = gyre_ad_trans_t(cx, pt)
         case('DZIEM')
            tr = dziem_ad_trans_t(cx, pt)
         case('JCD')
            if (cx%l == 0) then
               tr = rjcd_ad_trans_t(cx, pt)
            else
               tr = jcd_ad_trans_t(cx, pt)
            end if
         case('MIX')
            tr = mix_ad_trans_t(cx, pt)
         case('LAGP')
            tr = lagp_ad_trans_t(cx, pt)
         case default
            @:ABORT('invalid variables_set')
         end select

         ! Finish

         return

      end function ad_trans_t_${R}$_

   #:endfor

   !****

   function ad_ibound_conds_t(cx, os_p) result(bc)

      use bound_conds_m

      use gyre_ad_ibound_conds_m
      use dziem_ad_ibound_conds_m
      use jcd_ad_ibound_conds_m
      use rjcd_ad_ibound_conds_m
      use mix_ad_ibound_conds_m
      use lagp_ad_ibound_conds_m

      type(context_t), pointer, intent(in) :: cx
      type(osc_par_t), intent(in)          :: os_p
      class(bound_conds_rt), allocatable   :: bc

      ! Construct the ad_ibound_conds type

      select case(os_p%variables_set)
      case('GYRE')
         bc = gyre_ad_ibound_conds_t(cx, os_p)
      case('DZIEM')
         bc = dziem_ad_ibound_conds_t(cx, os_p)
      case('JCD')
         if (cx%l == 0) then
            bc = rjcd_ad_ibound_conds_t(cx, os_p)
         else
            bc = jcd_ad_ibound_conds_t(cx, os_p)
         end if
      case('MIX')
         bc = mix_ad_ibound_conds_t(cx, os_p)
      case('LAGP')
         bc = lagp_ad_ibound_conds_t(cx, os_p)
      case default
         @:ABORT('invalid variables_set')
      end select

      ! Finish

      return

   end function ad_ibound_conds_t

   !****

   function ad_obound_conds_t(cx, os_p) result(bc)

      use bound_conds_m

      use gyre_ad_obound_conds_m
      use dziem_ad_obound_conds_m
      use jcd_ad_obound_conds_m
      use rjcd_ad_obound_conds_m
      use mix_ad_obound_conds_m
      use lagp_ad_obound_conds_m

      type(context_t), pointer, intent(in) :: cx
      type(osc_par_t), intent(in)          :: os_p
      class(bound_conds_rt), allocatable   :: bc

      ! Construct the ad_obound_conds type

      select case(os_p%variables_set)
      case('GYRE')
         bc = gyre_ad_obound_conds_t(cx, os_p)
      case('DZIEM')
         bc = dziem_ad_obound_conds_t(cx, os_p)
      case('JCD')
         if (cx%l == 0) then
            bc = rjcd_ad_obound_conds_t(cx, os_p)
         else
            bc = jcd_ad_obound_conds_t(cx, os_p)
         end if
      case('MIX')
         bc = mix_ad_obound_conds_t(cx, os_p)
      case('LAGP')
         bc = lagp_ad_obound_conds_t(cx, os_p)
      case default
         @:ABORT('invalid variables_set')
      end select

      ! Finish

      return

   end function ad_obound_conds_t

end module ad_factory_m
