! Module  : ad_ibound_conds_m
! Purpose : adiabatic inner boundary conditions
!
! Copyright 2013-2026 Rich Townsend & The GYRE Team
!
! This file is part of GYRE. GYRE is free software: you can
! redistribute it and/or modify it under the terms of the GNU General
! Public License as published by the Free Software Foundation, version 3.
!
! GYRE is distributed in the hope that it will be useful, but WITHOUT
! ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
! or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
! License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.

#:include 'gyre.inc'

#:set P = os.path.basename(_FILE_).split('_')[0]

module ${P}$_ad_ibound_conds_m

   ! Uses

   use forum_m, only: RD

   use bound_conds_m
   use context_m
   use model_m
   use model_util_m
   use osc_par_m
   use point_m
   use state_m

   use ISO_FORTRAN_ENV

   ! No implicit typing

   implicit none (type, external)

   ! Derived-type definitions

   type, extends(bound_conds_rt) :: ${P}$_ad_ibound_conds_t
      private
      type(context_t), pointer  :: cx => null()
      real(RD)                  :: V_2
      real(RD)                  :: c_1
      procedure(eval_), pointer :: eval_
   contains
      private
      procedure, public :: eval
   end type ${P}$_ad_ibound_conds_t

   ! Interfaces

   interface
      subroutine eval_(this, st, B, s, trans)
         use forum_m, only: RD
         use state_m
         import ${P}$_ad_ibound_conds_t
         implicit none (type, external)
         class(${P}$_ad_ibound_conds_t), intent(in)  :: this
         class(state_rt), intent(in)                 :: st
         real(RD), contiguous, intent(out)           :: B(:,:)
         real(RD), contiguous, intent(out), optional :: s(:)
         logical, intent(in), optional               :: trans
      end subroutine eval_
   end interface

   interface ${P}$_ad_ibound_conds_t
      module procedure ${P}$_ad_ibound_conds_t_
   end interface ${P}$_ad_ibound_conds_t

   ! Access specifiers

   public :: ${P}$_ad_ibound_conds_t

   ! Default access

   private

contains

   function ${P}$_ad_ibound_conds_t_(cx, os_p) result(bc)

      type(context_t), pointer, intent(in) :: cx
      type(osc_par_t), intent(in)          :: os_p
      type(${P}$_ad_ibound_conds_t)        :: bc

      class(model_t), pointer :: ml
      type(point_t)           :: pt

      ! Construct the ad_ibound_conds type

      ml => cx%model()
      pt = cx%point_i()

      select case (os_p%inner_bound)
      case ('REGULAR')
         @:ASSERT(pt%x == 0._RD, 'boundary condition invalid for x /= 0')
         bc%eval_ => eval_regular_
      case ('ZERO_R')
         @:ASSERT(pt%x /= 0._RD, 'boundary condition invalid for x == 0')
         bc%eval_ => eval_zero_r_
      case ('ZERO_H')
         @:ASSERT(pt%x /= 0._RD, 'boundary condition invalid for x == 0')
         bc%eval_ => eval_zero_h_
      case default
         @:ABORT('invalid inner_bound')
      end select

      bc%cx => cx

      ! Store structure coefficients

      call check_model(ml, [I_V_2,I_C_1])

      bc%V_2 = ml%coeff(I_V_2, pt)
      bc%c_1 = ml%coeff(I_C_1, pt)

      ! Other initializations

      bc%n_b = 2
      bc%n_e = 4

      ! Finish

      return

   end function ${P}$_ad_ibound_conds_t_

   !****

   subroutine eval(this, st, B, s, trans)

      class(${P}$_ad_ibound_conds_t), intent(in)  :: this
      class(state_rt), intent(in)                 :: st
      real(RD), contiguous, intent(out)           :: B(:,:)
      real(RD), contiguous, intent(out), optional :: s(:)
      logical, intent(in), optional               :: trans

      ! Evaluate the inner boundary conditions

      call this%eval_(st, B, s, trans)

      ! Finish

      return

   end subroutine eval

   !****

   subroutine eval_regular_(this, st, B, s, trans)

      class(${P}$_ad_ibound_conds_t), intent(in)  :: this
      class(state_rt), intent(in)                 :: st
      real(RD), contiguous, intent(out)           :: B(:,:)
      real(RD), contiguous, intent(out), optional :: s(:)
      logical, intent(in), optional               :: trans

      logical  :: trans_
      real(RD) :: omega_c
      real(RD) :: lambda
      real(RD) :: l_i

      if (PRESENT(trans)) then
         trans_ = trans
      else
         trans_ = .FALSE.
      end if

      if (trans_) then
         @:CHECK_BOUNDS(SIZE(B, 1), this%n_e)
         @:CHECK_BOUNDS(SIZE(B, 2), this%n_b)
      else
         @:CHECK_BOUNDS(SIZE(B, 1), this%n_b)
         @:CHECK_BOUNDS(SIZE(B, 2), this%n_e)
      end if

      if (PRESENT(s)) then
         @:CHECK_BOUNDS(SIZE(s), this%n_e)
      end if

      ! Evaluate the inner boundary conditions matrix and
      ! inhomogeneous vector (regularity-enforcing)

      associate( &
         y_T_1 => st%y_T_1, &
         omega => st%omega, &
         V_2 => this%V_2, &
         c_1 => this%c_1, &
         Omega_rot => this%cx%Omega_rot_i, &
         alpha_grv => this%cx%alpha_grv, &
         alpha_omg => this%cx%alpha_omg, &
         m => this%cx%m)

         omega_c = omega - m*Omega_rot

         lambda = this%cx%lambda(Omega_rot, st)
         l_i = this%cx%l_e(Omega_rot, st)

         #:include 'IB_regular.inc'

      end associate

      ! Finish

      return

   end subroutine eval_regular_

   !****

   subroutine eval_zero_r_(this, st, B, s, trans)

      class(${P}$_ad_ibound_conds_t), intent(in)  :: this
      class(state_rt), intent(in)                 :: st
      real(RD), contiguous, intent(out)           :: B(:,:)
      real(RD), contiguous, intent(out), optional :: s(:)
      logical, intent(in), optional               :: trans

      logical :: trans_

      if (PRESENT(trans)) then
         trans_ = trans
      else
         trans_ = .FALSE.
      end if

      if (trans_) then
         @:CHECK_BOUNDS(SIZE(B, 1), this%n_e)
         @:CHECK_BOUNDS(SIZE(B, 2), this%n_b)
      else
         @:CHECK_BOUNDS(SIZE(B, 1), this%n_b)
         @:CHECK_BOUNDS(SIZE(B, 2), this%n_e)
      end if

      if (PRESENT(s)) then
         @:CHECK_BOUNDS(SIZE(s), this%n_e)
      end if

      ! Evaluate the inner boundary condition matrix and inhomogeneous
      ! vector (zero radial displacement/gravity)

      associate( &
         alpha_grv => this%cx%alpha_grv)

         #:include 'IB_zero_r.inc'

      end associate

      ! Finish

      return

   end subroutine eval_zero_r_

   !****

   subroutine eval_zero_h_(this, st, B, s, trans)

      class(${P}$_ad_ibound_conds_t), intent(in)  :: this
      class(state_rt), intent(in)                 :: st
      real(RD), contiguous, intent(out)           :: B(:,:)
      real(RD), contiguous, intent(out), optional :: s(:)
      logical, intent(in), optional               :: trans

      logical  :: trans_
      real(RD) :: omega_c
      real(RD) :: lambda

      if (PRESENT(trans)) then
         trans_ = trans
      else
         trans_ = .FALSE.
      end if

      if (trans_) then
         @:CHECK_BOUNDS(SIZE(B, 1), this%n_e)
         @:CHECK_BOUNDS(SIZE(B, 2), this%n_b)
      else
         @:CHECK_BOUNDS(SIZE(B, 1), this%n_b)
         @:CHECK_BOUNDS(SIZE(B, 2), this%n_e)
      end if

      if (PRESENT(s)) then
         @:CHECK_BOUNDS(SIZE(s), this%n_e)
      end if

      ! Evaluate the inner boundary condition matrix (zero horizontal
      ! displacement/gravity)

      associate( &
         omega => st%omega, &
         y_T_1 => st%y_T_1, &
         V_2 => this%V_2, &
         c_1 => this%c_1, &
         Omega_rot => this%cx%Omega_rot_i, &
         alpha_grv => this%cx%alpha_grv, &
         alpha_omg => this%cx%alpha_omg, &
         m => this%cx%m)

         omega_c = omega - m*Omega_rot

         lambda = this%cx%lambda(Omega_rot, st)

         ! Set up the matrix

         #:include 'IB_zero_h.inc'

      end associate

      ! Finish

      return

   end subroutine eval_zero_h_

end module ${P}$_ad_ibound_conds_m
