# File     : Makefile
# Purpose  : makefile for math unit-testing subdir

# Variables

TARGETS=test_gyre_func

# Flags

HDF5=yes
DEBUG=yes

LDFLAGS=`mesasdk_hdf5_link`

# Include other makefiles

SUBDIRS=..:../../extern/core

include ../../build/Make.inc
