# File     : Makefile
# Purpose  : makefile for test/ad subdir

# Variables

SUBDIRS=num poly fgong losc mesa

# Rules

test :
	@for DIR in ${SUBDIRS}; do \
            make -C $${DIR}; \
        done

build_ref build_ref_arch :
	@for DIR in ${SUBDIRS}; do \
            make -C $${DIR} $@; \
        done

.PHONY: test build_ref build_ref_arch
