# File     : Makefile
# Purpose  : makefile for src/wos subdir

# Variables

TARGETS=gyre_step

# Flags

HDF5=yes

LDFLAGS=`mesasdk_hdf5_link`

# Include other makefiles

SUBDIRS=../extern/core:../common:../ivp:../bvp:../matrix:../ext:../search

include ../Make.inc
