! Module  : linalg_m
! Purpose : linear algebra
!
! Copyright 2013-2026 Rich Townsend & The GYRE Team
!
! This file is part of GYRE. GYRE is free software: you can
! redistribute it and/or modify it under the terms of the GNU General
! Public License as published by the Free Software Foundation, version 3.
!
! GYRE is distributed in the hope that it will be useful, but WITHOUT
! ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
! or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
! License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.

#:include 'gyre.inc'

module linalg_m

   ! Uses

   use forum_m, only: RD

   use blas_lapack_m
   use math_m

   use ISO_FORTRAN_ENV

   ! No implicit typing

   implicit none (type, external)

   #:for S in FLOAT_SUFFIXES

      ! Interfaces

      interface eigen_decompose
         module procedure eigen_decompose_gen_${S}$_
      end interface eigen_decompose

      #:for N in [2, 4, 6]
         interface eigen_decompose_${N}$
            module procedure eigen_decompose_${N}$_${S}$_
         end interface eigen_decompose_${N}$
      #:endfor

      interface sing_decompose
         module procedure sing_decompose_${S}$_
      end interface sing_decompose

      interface trans_solve
         module procedure trans_solve_gen_${S}$_
      end interface trans_solve

      #:for N in [2, 4, 6]
         interface trans_solve_${N}$
            module procedure trans_solve_${N}$_${S}$_
         end interface trans_solve_${N}$
      #:endfor

      interface commutator
         module procedure commutator_${S}$_
      end interface commutator

      interface diagonal
         module procedure diagonal_${S}$_
      end interface diagonal

      interface diagonal_matrix
         module procedure diagonal_matrix_${S}$_
      end interface diagonal_matrix

   #:endfor

   ! Access specifiers

   public :: eigen_decompose
   public :: eigen_decompose_2
   public :: eigen_decompose_4
   public :: eigen_decompose_6
   public :: sing_decompose
   public :: trans_solve
   public :: trans_solve_2
   public :: trans_solve_4
   public :: trans_solve_6
   public :: commutator
   public :: diagonal
   public :: diagonal_matrix
   public :: identity_matrix

   ! Default access

   private

contains

   #:for T, S in zip(FLOAT_TYPES, FLOAT_SUFFIXES)

      subroutine eigen_decompose_2_${S}$_(A, lambda, V_l, V_r)

         ${T}$, intent(in)                  :: A(:,:)
         complex(RD), intent(out)           :: lambda(:)
         complex(RD), intent(out), optional :: V_l(:,:)
         complex(RD), intent(out), optional :: V_r(:,:)

         ${T}$       :: b
         ${T}$       :: c
         complex(RD) :: s
         complex(RD) :: q
         complex(RD) :: V_l_(2,2)
         complex(RD) :: V_r_(2,2)
         integer     :: i

         @:CHECK_BOUNDS(SIZE(A, 1), 2)
         @:CHECK_BOUNDS(SIZE(A, 2), 2)

         @:CHECK_BOUNDS(SIZE(lambda), 2)

         if(PRESENT(V_l)) then
            @:CHECK_BOUNDS(SIZE(V_l, 1), 2)
            @:CHECK_BOUNDS(SIZE(V_l, 2), 2)
         endif

         if(PRESENT(V_r)) then
            @:CHECK_BOUNDS(SIZE(V_r, 1), 2)
            @:CHECK_BOUNDS(SIZE(V_r, 2), 2)
         endif

         ! Perform the eigendecomposition of the 2x2 matrix A

         ! Solve the quadratic for the eigenvalues

         b = -A(1,1) - A(2,2)
         c = A(1,1)*A(2,2) - A(1,2)*A(2,1)

         #:if T == 'real(RD)'
            s = sqrt(CMPLX(b**2 - 4._RD*c, KIND=RD))
            q = -0.5_RD*(b + SIGN(1._RD, b)*s)
         #:elif T == 'complex(RD)'
            s = sqrt(b**2 - 4._RD*c)
            q = -0.5_RD*(b + SIGN(1._RD, REAL(CONJG(b)*s))*s)
         #:else
            #:stop f'invalid type {T}'
         #:endif

         lambda(1) = q
         lambda(2) = c/q

         ! Calculate eigenvectors

         if(PRESENT(V_l) .OR. PRESENT(V_r)) then

            V_l_(1,1) = A(2,1)
            V_l_(1,2) = lambda(1) - A(1,1)

            V_l_(2,1) = A(2,1)
            V_l_(2,2) = lambda(2) - A(1,1)

            V_r_(1,1) = A(1,2)
            V_r_(2,1) = lambda(1) - A(1,1)

            V_r_(1,2) = A(1,2)
            V_r_(2,2) = lambda(2) - A(1,1)

            do i = 1,SIZE(A, 1)
               V_l_(i,:) = V_l_(i,:)/SUM(V_l_(i,:)*V_r_(:,i))
            enddo

            if(PRESENT(V_l)) then
               V_l = V_l_
            endif

            if(PRESENT(V_r)) then
               V_r = V_r_
            endif

         end if

         ! Finish

         return

      end subroutine eigen_decompose_2_${S}$_

   #:endfor

   !****

   #:for I, N in [ &
      ['4', 4], &
      ['6', 6], &
      ['gen', 'SIZE(A, 1)']]

      subroutine eigen_decompose_${I}$_r_(A, lambda, V_l, V_r)

         real(RD), intent(inout)  :: A(:,:)
         complex(RD), intent(out) :: lambda(:)
         complex(RD), intent(out) :: V_l(:,:)
         complex(RD), intent(out) :: V_r(:,:)

         real(RD)    :: lambda_re(${N}$)
         real(RD)    :: lambda_im(${N}$)
         real(RD)    :: V_l_r(${N}$,${N}$)
         real(RD)    :: V_r_r(${N}$,${N}$)
         real(RD)    :: work(4*${N}$)
         integer     :: info
         integer     :: i
         complex(RD) :: norm

         @:CHECK_BOUNDS(SIZE(A, 1), ${N}$)
         @:CHECK_BOUNDS(SIZE(A, 2), ${N}$)

         @:CHECK_BOUNDS(SIZE(lambda), ${N}$)

         @:CHECK_BOUNDS(SIZE(V_l, 1), ${N}$)
         @:CHECK_BOUNDS(SIZE(V_l, 2), ${N}$)

         @:CHECK_BOUNDS(SIZE(V_r, 1), ${N}$)
         @:CHECK_BOUNDS(SIZE(V_r, 2), ${N}$)

         ! Perform the eigendecomposition of A

         call XGEEV('V', 'V', ${N}$, A, ${N}$, lambda_re, lambda_im, &
            V_l_r, ${N}$, V_r_r, ${N}$, work, SIZE(work), info)
         @:ASSERT(info == 0, 'non-zero return from XGEEV')

         lambda = CMPLX(lambda_re, lambda_im, RD)

         call reconstruct_eigenvector_(lambda_re, lambda_im, V_l_r, V_l)
         call reconstruct_eigenvector_(lambda_re, lambda_im, V_r_r, V_r)

         V_l = CONJG(TRANSPOSE(V_l))

         ! Renormalize the left eigenvectors so they are orthonormal to
         ! the right eigenvectors

         do i = 1, ${N}$
            norm = SUM(V_l(i,:)*V_r(:,i))
            V_l(i,:) = V_l(i,:)/norm
         enddo

         ! Finish

         return

      contains

         subroutine reconstruct_eigenvector_(lambda_re, lambda_im, V_r, V)

            real(RD), intent(in)     :: lambda_re(:)
            real(RD), intent(in)     :: lambda_im(:)
            real(RD), intent(in)     :: V_r(:,:)
            complex(RD), intent(out) :: V(:,:)

            integer :: i

            ! Reconstruct the complex eigenvector

            i = 1

            recon_loop : do

               if(lambda_im(i) == 0._RD) then

                  V(:,i) = V_r(:,i)

                  i = i + 1

               elseif(lambda_re(i) == lambda_re(i+1) .AND. &
                      lambda_im(i) == -lambda_im(i+1)) then

                  V(:,i) = CMPLX(V_r(:,i), V_r(:,i+1), KIND=RD)
                  V(:,i+1) = CONJG(V(:,i))

                  i = i + 2

               else

                  @:ABORT('Complex eigenvalue does not have conjugate pair')

               endif

               if(i > ${N}$) exit recon_loop

            end do recon_loop

            ! Finish

            return

         end subroutine reconstruct_eigenvector_

      end subroutine eigen_decompose_${I}$_r_

      !****

      subroutine eigen_decompose_${I}$_c_(A, lambda, V_l, V_r)

         complex(RD), intent(inout)    :: A(:,:)
         complex(RD), intent(out)      :: lambda(:)
         complex(RD), intent(out)      :: V_l(:,:)
         complex(RD), intent(out)      :: V_r(:,:)

         complex(RD) :: work(2*${N}$)
         real(RD)    :: rwork(2*${N}$)
         integer     :: info
         integer     :: i
         complex(RD) :: norm

         @:CHECK_BOUNDS(SIZE(A, 2), ${N}$)
         @:CHECK_BOUNDS(SIZE(lambda), ${N}$)

         @:CHECK_BOUNDS(SIZE(V_l, 1), ${N}$)
         @:CHECK_BOUNDS(SIZE(V_l, 2), ${N}$)

         @:CHECK_BOUNDS(SIZE(V_r, 1), ${N}$)
         @:CHECK_BOUNDS(SIZE(V_r, 2), ${N}$)

         ! Perform the eigendecomposition of A

         call XGEEV('V', 'V', ${N}$, A, ${N}$, lambda, &
            V_l, ${N}$, V_r, ${N}$, work, SIZE(work, 1), rwork, info)
         @:ASSERT(info == 0, 'non-zero return from XGEEV')

         V_l = CONJG(TRANSPOSE(V_l))

         ! Renormalize the left eigenvectors so they are orthonormal to
         ! the right eigenvectors

         do i = 1, ${N}$
            norm = SUM(V_l(i,:)*V_r(:,i))
            V_l(i,:) = V_l(i,:)/norm
         enddo

         ! Finish

         return

      end subroutine eigen_decompose_${I}$_c_

   #:endfor

   !****

   #:for T, S in zip(FLOAT_TYPES, FLOAT_SUFFIXES)

      #:for I, N in [ &
            ['2', 2], &
            ['4', 4], &
            ['6', 6], &
            ['gen', 'SIZE(A_t, 1)']]

         subroutine trans_solve_${I}$_${S}$_(A_t, B_t)

            ${T}$, contiguous, intent(inout) :: A_t(:,:)
            ${T}$, contiguous, intent(inout) :: B_t(:,:)

            integer  :: i
            integer  :: j
            real(RD) :: piv
            real(RD) :: piv_tmp
            integer  :: i_piv
            ${T}$    :: piv_row_A(${N}$)
            ${T}$    :: piv_row_B(SIZE(B_t, 1))
            ${T}$    :: alpha
            ${T}$    :: beta

            @:CHECK_BOUNDS(SIZE(A_t, 2), ${N}$)
            @:CHECK_BOUNDS(SIZE(B_t, 2), ${N}$)

            ! Solve the linear system A X = B using Gaussian
            ! elimination. The arrays A_t and B_t provide the
            ! transposes of A and B, and on return the transpose of X
            ! is stored in B_t

            associate (n => ${N}$)

               ! First reduce A to upper triangular form

               reduce_loop: do j = 1, n

                  ! Find the pivot row

                  piv = 0._RD
                  i_piv = j

                  do i = j, n
                     piv_tmp = abs(A_t(j,i))
                     if (piv_tmp > piv) then
                        piv = piv_tmp
                        i_piv = i
                     end if
                  end do

                  @:ASSERT(piv /= 0, 'zero pivot')

                  ! If necessary, swap rows to place the pivot
                  ! on the diagonal

                  if (i_piv /= j) then

                     piv_row_A = A_t(:,i_piv)
                     A_t(:,i_piv) = A_t(:,j)
                     A_t(:,j) = piv_row_A

                     piv_row_B = B_t(:,i_piv)
                     B_t(:,i_piv) = B_t(:,j)
                     B_t(:,j) = piv_row_B

                  else

                     piv_row_A = A_t(:,j)
                     piv_row_B = B_t(:,j)

                  end if

                  ! Eliminate elements below the diagonal

                  alpha = 1._RD/A_t(j,j)

                  do concurrent(i = j+1:n) local(beta)
                     beta = alpha*A_t(j,i)
                     A_t(:,i) = A_t(:,i) - beta*piv_row_A
                     B_t(:,i) = B_t(:,i) - beta*piv_row_B
                  end do

               end do reduce_loop

               ! Now perform back-substitution

               B_t(:,n) = B_t(:,n)/A_t(n,n)

               backsub_loop: do i = n-1, 1, -1

                  do j = 1, SIZE(B_t, 1)
                     B_t(j,i) = (B_t(j,i) - SUM(A_t(i+1:n,i)*B_t(j,i+1:n)))/A_t(i,i)
                  end do

               end do backsub_loop

            end associate

            ! Finish

            return

         end subroutine trans_solve_${I}$_${S}$_

      #:endfor

      !****

      function commutator_${S}$_(A, B) result(C)

         ${T}$, intent(in) :: A(:,:)
         ${T}$, intent(in) :: B(:,:)
         ${T}$             :: C(SIZE(A, 1),SIZE(A, 2))

         @:CHECK_BOUNDS(SIZE(A, 1), SIZE(A, 2))

         @:CHECK_BOUNDS(SIZE(B, 1), SIZE(B, 2))
         @:CHECK_BOUNDS(SIZE(B, 1), SIZE(A, 1))

         ! Calculate the commutator [A,B]

         C = MATMUL(A, B) - MATMUL(B, A)

         ! Finish

         return

      end function commutator_${S}$_

      !****

      pure function diagonal_${S}$_(A) result(D)

         ${T}$, intent(in) :: A(:,:)
         ${T}$             :: d(MIN(SIZE(A, 1),SIZE(A, 2)))

         integer :: i

         ! Extract the diagonal elements of matrix A

         do i = 1,SIZE(d)
            d(i) = A(i,i)
         end do

         ! Finish

         return

      end function diagonal_${S}$_

      !****

      pure function diagonal_matrix_${S}$_(x) result(D)

         ${T}$, intent(in) :: x(:)
         ${T}$             :: D(SIZE(x), SIZE(x))

         integer :: i

         ! Set up the diagonal matrix with elements x

         D = 0._RD

         do i = 1,SIZE(x)
            D(i,i) = x(i)
         end do

         ! Finish

         return

      end function diagonal_matrix_${S}$_

   #:endfor

   !****

   subroutine sing_decompose_r_(A, sigma, U, V_H)

      real(RD), intent(inout) :: A(:,:)
      real(RD), intent(out)   :: sigma(:)
      real(RD), intent(out)   :: U(:,:)
      real(RD), intent(out)   :: V_H(:,:)

      integer  :: n
      real(RD) :: work(5*SIZE(A, 1))
      integer  :: info

      @:CHECK_BOUNDS(SIZE(sigma), MIN(SIZE(A, 1), SIZE(A, 2)))

      @:CHECK_BOUNDS(SIZE(U, 1), SIZE(A, 1))
      @:CHECK_BOUNDS(SIZE(U, 2), SIZE(A, 1))

      @:CHECK_BOUNDS(SIZE(V_H, 1), SIZE(A, 2))
      @:CHECK_BOUNDS(SIZE(V_H, 2), SIZE(A, 2))

      ! Perform the singular-value decomposition of A

      n = SIZE(A, 1)

      call XGESVD('A', 'A', n, n, A, n, sigma, U, n, V_H, n, work, SIZE(work), info)
      @:ASSERT(info == 0, 'non-zero return from XGESVD')

      ! Finish

      return

   end subroutine sing_decompose_r_

   !****

   subroutine sing_decompose_c_(A, sigma, U, V_H)

      complex(RD), intent(inout) :: A(:,:)
      real(RD), intent(out)      :: sigma(:)
      complex(RD), intent(out)   :: U(:,:)
      complex(RD), intent(out)   :: V_H(:,:)

      integer     :: n
      complex(RD) :: work(3*SIZE(A, 1))
      real(RD)    :: rwork(5*SIZE(A, 1))
      integer     :: info

      @:CHECK_BOUNDS(SIZE(sigma),MIN(SIZE(A, 1), SIZE(A, 2)))

      @:CHECK_BOUNDS(SIZE(U, 1),SIZE(A, 1))
      @:CHECK_BOUNDS(SIZE(U, 2),SIZE(A, 1))

      @:CHECK_BOUNDS(SIZE(V_H, 1),SIZE(A, 2))
      @:CHECK_BOUNDS(SIZE(V_H, 2),SIZE(A, 2))

      ! Perform the singular-value decomposition of A

      n = SIZE(A, 1)

      call XGESVD('A', 'A', n, n, A, n, sigma, U, n, V_H, n, work, SIZE(work), rwork, info)
      @:ASSERT(info == 0, 'non-zero return from XGESVD')

      ! Finish

      return

   end subroutine sing_decompose_c_

   !****

   pure function identity_matrix(n) result(I)

      integer, intent(in) :: n
      real(RD)            :: I(n,n)

      integer :: j

      ! Set up the rank-n identity matrix

      I = 0._RD

      do j = 1,n
         I(j,j) = 1._RD
      end do

      ! Finish

      return

   end function identity_matrix

end module linalg_m
