! Module  : sysblock_elem_m
! Purpose : array element storage for sysblock_t
!
! Copyright 2013-2026 Rich Townsend & The GYRE Team
!
! This file is part of GYRE. GYRE is free software: you can
! redistribute it and/or modify it under the terms of the GNU General
! Public License as published by the Free Software Foundation, version 3.
!
! GYRE is distributed in the hope that it will be useful, but WITHOUT
! ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
! or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
! License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.

#:include 'gyre.inc'

module sysblock_elem_m

   ! Uses

   use sysblock_m

   ! No implicit typing

   implicit none (type, external)

   #:for T, S in zip(DTYPE_BASE_TYPES, DTYPE_SUFFIXES)

      ! Derived-type definitions

      type :: sysblock_elem_${S}$
         class(sysblock_${S}$), allocatable :: sb
      end type sysblock_elem_${S}$

      ! Interfaces

      ! Access specifiers

      public :: sysblock_elem_${S}$

   #:endfor

   ! Default access

   private

end module sysblock_elem_m
