# File     : Makefile
# Purpose  : makefile for src/ad subdir

# Variables

TARGETS=gyre_ad

# Flags

HDF5=yes

LDFLAGS=`mesasdk_hdf5_link`

# Include other makefiles

SUBDIRS=../extern/core:../common:../ivp:../bvp:../coeffs:../matrix:../ext:../frontend:../rad

include ../Make.inc
