! Module  : match_diff_m
! Purpose : difference equations (match conditions)
!
! Copyright 2013-2026 Rich Townsend & The GYRE Team
!
! This file is part of GYRE. GYRE is free software: you can
! redistribute it and/or modify it under the terms of the GNU General
! Public License as published by the Free Software Foundation, version 3.
!
! GYRE is distributed in the hope that it will be useful, but WITHOUT
! ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
! or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
! License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.

#:include 'gyre.inc'

module match_diff_m

   ! Uses

   use forum_m, only: RD

   use diff_m
   use eqns_m
   use ext_m
   use math_m
   use point_m
   use state_m

   use ISO_FORTRAN_ENV

   ! No implicit typing

   implicit none (type, external)

   #:for T, S in zip(DTYPE_BASE_TYPES, DTYPE_SUFFIXES)

      ! Derived-type definitions

      type, extends(diff_${S}$) :: match_diff_${S}$
         private
         class(eqns_${S}$), allocatable :: eq(:)
         real(RD)                       :: dx
      contains
         private
         procedure, public :: eval => eval_${S}$_
      end type match_diff_${S}$

      ! Interfaces

      interface match_diff_${S}$
         module procedure match_diff_${S}$_
      end interface match_diff_${S}$

      ! Access specifiers

      public :: match_diff_${S}$

   #:endfor

   ! Default access

   private

contains

   #:for T, S in zip(DTYPE_BASE_TYPES, DTYPE_SUFFIXES)

      function match_diff_${S}$_(eqns_factory, pt_a, pt_b) result(df)

         interface
            subroutine eqns_factory(pt, eq)
               use point_m
               use eqns_m
               implicit none (type, external)
               type(point_t), intent(in)                   :: pt(:)
               class(eqns_${S}$), allocatable, intent(out) :: eq(:)
            end subroutine eqns_factory
         end interface
         type(point_t), intent(in) :: pt_a
         type(point_t), intent(in) :: pt_b
         type(match_diff_${S}$)    :: df

         @:ASSERT_DEBUG(pt_b%s == pt_a%s+1, 'segment mismatch')
         @:ASSERT_DEBUG(pt_b%x == pt_a%x, 'segment mismatch')

         ! Construct the match_diff type

         call eqns_factory([pt_a,pt_b], df%eq)

         df%n_e = df%eq(1)%n_e
         @:ASSERT_DEBUG(ALL(df%eq%n_e == df%n_e))
         df%n_v = 2*df%n_e

         ! Finish

         return

      end function match_diff_${S}$_

      !****

      subroutine eval_${S}$_(this, st, E, scl, F, trans)

         class(match_diff_${S}$), intent(in)      :: this
         class(state_${S}$), intent(in)           :: st
         ${T}$, contiguous, intent(out)           :: E(:,:)
         type(ext_${S}$), intent(out)             :: scl
         ${T}$, contiguous, intent(out), optional :: F(:)
         logical, intent(in), optional            :: trans

         logical :: trans_
         ${T}$   :: C_1(this%n_e,this%n_e)
         ${T}$   :: C_2(this%n_e,this%n_e)
         ${T}$   :: F_1(this%n_e)
         ${T}$   :: F_2(this%n_e)

         if (PRESENT(trans)) then
            trans_ = trans
         else
            trans_ = .FALSE.
         end if

         if (trans_) then
            @:CHECK_BOUNDS(SIZE(E, 1), this%n_v)
            @:CHECK_BOUNDS(SIZE(E, 2), this%n_e)
         else
            @:CHECK_BOUNDS(SIZE(E, 1), this%n_e)
            @:CHECK_BOUNDS(SIZE(E, 2), this%n_v)
         end if

         if (PRESENT(F)) then
            @:CHECK_BOUNDS(SIZE(F), this%n_e)
         end if

         ! Evaluate the difference equations

         associate (n_e => this%n_e)

            if (PRESENT(F)) then

               call this%eq(1)%eval_C(st, C_1, F=F_1, trans=trans)
               call this%eq(2)%eval_C(st, C_2, F=F_2, trans=trans)

            else

               call this%eq(1)%eval_C(st, C_1, trans=trans)
               call this%eq(2)%eval_C(st, C_2, trans=trans)

            end if

            if (trans) then

               E(:n_e,:) = C_1
               E(n_e+1:,:) = -C_2

            else

               E(:,:n_e) = C_1
               E(:,n_e+1:) = -C_2

            end if

            if (PRESENT(F)) then
               F = F_1 - F_2
            end if

            scl = ONE_${S}$

         end associate

         ! Finish

      end subroutine eval_${S}$_

   #:endfor

end module match_diff_m
