! Module  : trapz_diff_m
! Purpose : difference equations (quasi-trapezoidal)
!
! Copyright 2013-2026 Rich Townsend & The GYRE Team
!
! This file is part of GYRE. GYRE is free software: you can
! redistribute it and/or modify it under the terms of the GNU General
! Public License as published by the Free Software Foundation, version 3.
!
! GYRE is distributed in the hope that it will be useful, but WITHOUT
! ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
! or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
! License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.

#:include 'gyre.inc'

module trapz_diff_m

   ! Uses

   use forum_m, only: RD

   use diff_m
   use eqns_m
   use ext_m
   use point_m
   use state_m
   use sysblock_m

   use ISO_FORTRAN_ENV

   ! No implicit typing

   implicit none (type, external)

   #:for S in DTYPE_SUFFIXES

      ! Derived-type definitions

      type, extends(diff_${S}$) :: trapz_diff_${S}$
         private
         class(eqns_${S}$), allocatable :: eq(:)
         real(RD), allocatable          :: w(:)
         real(RD)                       :: dx
         real(RD)                       :: x_m
         logical                        :: origin
      contains
         private
         procedure, public :: eval => eval_${S}$_
      end type trapz_diff_${S}$

      ! Interfaces

      interface trapz_diff_${S}$
         module procedure trapz_diff_${S}$_
      end interface trapz_diff_${S}$

      ! Access specifiers

      public :: trapz_diff_${S}$

   #:endfor

   ! Default access

   private

contains

   #:for T, S in zip(DTYPE_BASE_TYPES, DTYPE_SUFFIXES)

      function trapz_diff_${S}$_(eqns_factory, pt_a, pt_b, w) result(df)

         interface
            subroutine eqns_factory(pt, eq)
               use point_m
               use eqns_m
               implicit none (type, external)
               type(point_t), intent(in)                   :: pt(:)
               class(eqns_${S}$), allocatable, intent(out) :: eq(:)
            end subroutine eqns_factory
         end interface
         type(point_t), intent(in)      :: pt_a
         type(point_t), intent(in)      :: pt_b
         real(RD), intent(in), optional :: w(:)
         type(trapz_diff_${S}$)         :: df

         type(point_t) :: pt(2)

         @:ASSERT_DEBUG(pt_a%s == pt_b%s, 'segment mismatch')

         ! Construct the trapz_diff_t

         df%dx = pt_b%x - pt_a%x
         df%x_m = 0.5_RD*(pt_a%x + pt_b%x)

         pt = [pt_a,pt_b]

         call eqns_factory(pt, df%eq)

         df%origin = pt_a%x == 0._RD

         df%n_e = df%eq(1)%n_e
         @:ASSERT_DEBUG(ALL(df%eq%n_e == df%n_e))
         df%n_v = 2*df%n_e

         if (PRESENT(w)) then
            @:CHECK_BOUNDS(SIZE(w), df%n_e)
            df%w = w
         else
            allocate(df%w(df%n_e))
            df%w = 0.5_RD
         end if

         ! Finish

         return

      end function trapz_diff_${S}$_

      !****

      subroutine eval_${S}$_(this, st, E, scl, F, trans)

         class(trapz_diff_${S}$), intent(in)      :: this
         class(state_${S}$), intent(in)           :: st
         ${T}$, contiguous, intent(out)           :: E(:,:)
         type(ext_${S}$), intent(out)             :: scl
         ${T}$, contiguous, intent(out), optional :: F(:)
         logical, intent(in), optional            :: trans

         logical :: trans_
         ${T}$   :: A_1(this%n_e,this%n_e)
         ${T}$   :: A_2(this%n_e,this%n_e)
         ${T}$   :: F_1(this%n_e)
         ${T}$   :: F_2(this%n_e)
         integer :: i

         if (PRESENT(trans)) then
            trans_ = trans
         else
            trans_ = .FALSE.
         end if

         if (trans_) then
            @:CHECK_BOUNDS(SIZE(E, 1), this%n_v)
            @:CHECK_BOUNDS(SIZE(E, 2), this%n_e)
         else
            @:CHECK_BOUNDS(SIZE(E, 1), this%n_e)
            @:CHECK_BOUNDS(SIZE(E, 2), this%n_v)
         end if

         if (PRESENT(F)) then
            @:CHECK_BOUNDS(SIZE(F), this%n_e)
         end if

         ! Evaluate the difference equations

         associate (n_e => this%n_e)

            if (this%origin) then

               ! If we're at the origin, fudge things to avoid
               ! evaluating A and F there

               E = 0._RD

               if (PRESENT(F)) then
                  F = 0._RD
               end if

            else

               if (PRESENT(F)) then
                  call this%eq(1)%eval_A(st, this%dx, A_1, F=F_1, trans=trans_)
                  call this%eq(2)%eval_A(st, this%dx, A_2, F=F_2, trans=trans_)
               else
                  call this%eq(1)%eval_A(st, this%dx, A_1, trans=trans_)
                  call this%eq(2)%eval_A(st, this%dx, A_2, trans=trans_)
               end if

               if (trans_) then

                  do concurrent(i = 1:n_e)
                     E(:n_e,i) = (1._RD - this%w(i))*A_1(:,i)
                     E(n_e+1:,i) = this%w(i)*A_2(:,i)
                  end do

               else

                  do concurrent(i = 1:n_e)
                     E(i,:n_e) = (1._RD - this%w(i))*A_1(i,:)
                     E(i,n_e+1:) = this%w(i)*A_2(i,:)
                  end do

               end if

               if (PRESENT(F)) then

                  do concurrent(i = 1:n_e)
                     F(i) = - (1._RD - this%w(i))*F_1(i) - this%w(i)*F_2(i)
                  end do

               end if

            end if

            if (trans_) then

               do concurrent(i = 1:n_e)
                  E(i,i) = E(i,i) + 1._RD
                  E(n_e+i,i) = E(n_e+i,i) - 1._RD
               end do

            else

               do concurrent(i = 1:n_e)
                  E(i,i) = E(i,i) + 1._RD
                  E(i,n_e+i) = E(i,n_e+i) - 1._RD
               end do

            end if

            scl = ONE_${S}$

         end associate

         ! Finish

      end subroutine eval_${S}$_

   #:endfor

end module trapz_diff_m
