! Module  : tnad_factory_m
! Purpose : factory methods for nonadiabatic (+turbulent convection) routines
!
! Copyright 2013-2026 Rich Townsend & The GYRE Team
!
! This file is part of GYRE. GYRE is free software: you can
! redistribute it and/or modify it under the terms of the GNU General
! Public License as published by the Free Software Foundation, version 3.
!
! GYRE is distributed in the hope that it will be useful, but WITHOUT
! ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
! or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
! License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.

#:include 'gyre.inc'

module tnad_factory_m

   ! Uses

   use forum_m, only: RD

   use context_m
   use osc_par_m
   use point_m

   use ISO_FORTRAN_ENV

   ! No implicit typing

   implicit none (type, external)

   ! Interfaces

   interface tnad_diff_eqns_t
      module procedure tnad_diff_eqns_t_0_
      module procedure tnad_diff_eqns_t_1_
   end interface tnad_diff_eqns_t

   interface tnad_trans_t
      module procedure tnad_trans_t_0_
      module procedure tnad_trans_t_1_
   end interface tnad_trans_t

   ! Access specifiers

   public :: tnad_diff_eqns_t
   public :: tnad_trans_t
   #:if defined('GFORTRAN_PR125610')
   public :: tnad_diff_eqns_t_0_
   public :: tnad_diff_eqns_t_1_
   public :: tnad_trans_t_0_
   public :: tnad_trans_t_1_
   #:endif

   ! Default access

   private

contains

   #:for R in (0, 1)

      function tnad_diff_eqns_t_${R}$_(cx, pt, os_p) result(de)

         use diff_eqns_m

         use gyre_tnad_diff_eqns_m

         type(context_t), pointer, intent(in) :: cx
         type(point_t), intent(in)            :: pt${ARRAY_SPEC(R)}$
         type(osc_par_t), intent(in)          :: os_p
         class(diff_eqns_ct), allocatable     :: de${ARRAY_SPEC(R)}$

         ! Construct the tnad_diff_eqns type

         select case(os_p%variables_set)
         case('GYRE')
            de = gyre_tnad_diff_eqns_t(cx, pt, os_p)
         case default
            @:ABORT('invalid variables_set')
         end select

         ! Finish

         return

      end function tnad_diff_eqns_t_${R}$_

      !****

      function tnad_trans_t_${R}$_(cx, pt, os_p) result(tr)

         use trans_m

         use gyre_nad_trans_m

         type(context_t), pointer, intent(in) :: cx
         type(point_t), intent(in)            :: pt${ARRAY_SPEC(R)}$
         type(osc_par_t), intent(in)          :: os_p
         class(trans_ct), allocatable         :: tr${ARRAY_SPEC(R)}$

         ! Construct the tnad_trans type

         select case(os_p%variables_set)
         case('GYRE')
            tr = gyre_nad_trans_t(cx, pt)
         case default
            @:ABORT('invalid variables_set')
         end select

         ! Finish

         return

      end function tnad_trans_t_${R}$_

   #:endfor

end module tnad_factory_m
