# File     : Makefile
# Purpose  : makefile for src/nad subdir

# Variables

TARGETS=gyre

# Flags

HDF5=yes

LDFLAGS=`mesasdk_hdf5_link`

# Include other makefiles

SUBDIRS=../extern/core:../extern/astro:../common:../diff:../bep:../interp:../model:../matrix:../search:../ext:../frontend:../ad:../rad:../nad:../rot:../trad:../mode:../sol:../grid

include ../Make.inc
