! Module  : diff_block_factory_m
! Purpose : factory procedures for diff_block_rt and diff_block_ct types
!
! Copyright 2013-2026 Rich Townsend & The GYRE Team
!
! This file is part of GYRE. GYRE is free software: you can
! redistribute it and/or modify it under the terms of the GNU General
! Public License as published by the Free Software Foundation, version 3.
!
! GYRE is distributed in the hope that it will be useful, but WITHOUT
! ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
! or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
! License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.

#:include 'gyre.inc'

module diff_block_factory_m

   ! Uses

   use forum_m, only: RD

   use diff_block_m
   use num_par_m
   use point_m

   use ISO_FORTRAN_ENV

   ! No implicit typing

   implicit none (type, external)

   #:for S in DTYPE_SUFFIXES

      ! Interfaces

      interface diff_block_${S}$
         module procedure diff_block_${S}$_
      end interface diff_block_${S}$

      ! Access specifiers

      public :: diff_block_${S}$

   #:endfor

   ! Default access

   private

contains

   #:for T, S in zip(DTYPE_BASE_TYPES, DTYPE_SUFFIXES)

      function diff_block_${S}$_(diff_eqns_factory, pt_a, pt_b, nm_p) result(db)

         use colloc_gl2_block_m
         use colloc_gl4_block_m
         use colloc_gl6_block_m

         use magnus_gl2_block_m
         use magnus_gl4_block_m
         use magnus_gl6_block_m

         use mirk_block_m
         use trapz_block_m

         interface
            subroutine diff_eqns_factory(pt, de)
               use diff_eqns_m
               use point_m
               implicit none (type, external)
               type(point_t), intent(in)                        :: pt(:)
               class(diff_eqns_${S}$), allocatable, intent(out) :: de(:)
            end subroutine diff_eqns_factory
         end interface
         type(point_t), intent(in)            :: pt_a
         type(point_t), intent(in)            :: pt_b
         type(num_par_t), intent(in)          :: nm_p
         class(diff_block_${S}$), allocatable :: db

         ! Construct the diff_block type

         select case (nm_p%diff_scheme)
         case ('COLLOC_GL2')
            db = colloc_gl2_block_${S}$(diff_eqns_factory, pt_a, pt_b)
         case ('COLLOC_GL4')
            db = colloc_gl4_block_${S}$(diff_eqns_factory, pt_a, pt_b)
         case ('COLLOC_GL6')
            db = colloc_gl6_block_${S}$(diff_eqns_factory, pt_a, pt_b)
         case ('MAGNUS_GL2')
            db = magnus_gl2_block_${S}$(diff_eqns_factory, pt_a, pt_b)
         case ('MAGNUS_GL4')
            db = magnus_gl4_block_${S}$(diff_eqns_factory, pt_a, pt_b)
         case ('MAGNUS_GL6')
            db = magnus_gl6_block_${S}$(diff_eqns_factory, pt_a, pt_b)
         case ('TRAPZ')
            db = trapz_block_${S}$(diff_eqns_factory, pt_a, pt_b)
         case ('MIRK')
            db = mirk_block_${S}$(diff_eqns_factory, pt_a, pt_b)
         case default
            @:ABORT('invalid diff_scheme')
         end select

         ! Finish

         return

      end function diff_block_${S}$_

   #:endfor

end module diff_block_factory_m
