# File     : Makefile
# Purpose  : makefile for standard ad subdir

# Rules

test :
	@./test.sh

build_ref :
	./gyre gyre.in; \
        for file in summary*.h5; do mv $$file ref/$$file; done

.PHONY: test build_ref
