! Module  : static_ibound_m
! Purpose : static-tide adiabatic inner boundary conditions
!
! Copyright 2013-2026 Rich Townsend & The GYRE Team
!
! This file is part of GYRE. GYRE is free software: you can
! redistribute it and/or modify it under the terms of the GNU General
! Public License as published by the Free Software Foundation, version 3.
!
! GYRE is distributed in the hope that it will be useful, but WITHOUT
! ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
! or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
! License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.

#:include 'gyre.inc'

module static_ibound_m

   ! Uses

   use forum_m, only: RD

   use bound_m
   use context_m
   use ext_m
   use model_m
   use model_util_m
   use osc_par_m
   use point_m
   use state_m

   use ISO_FORTRAN_ENV

   ! No implicit typing

   implicit none (type, external)

   ! Derived-type definitions

   type, extends(bound_rt) :: static_ibound_t
      private
      type(context_t), pointer  :: cx => null()
      procedure(eval_), pointer :: eval_
   contains
      private
      procedure, public :: eval
   end type static_ibound_t

   ! Interfaces

   interface
      subroutine eval_(this, st, B, F, trans)
         use forum_m, only: RD
         use state_m
         import static_ibound_t
         implicit none (type, external)
         class(static_ibound_t), intent(in)          :: this
         class(state_rt), intent(in)                 :: st
         real(RD), contiguous, intent(out)           :: B(:,:)
         real(RD), contiguous, intent(out), optional :: F(:)
         logical, intent(in), optional               :: trans
      end subroutine eval_
   end interface

   interface static_ibound_t
      module procedure static_ibound_t_
   end interface static_ibound_t

   ! Access specifiers

   public :: static_ibound_t

   ! Default access

   private

contains

   function static_ibound_t_(cx, os_p) result(bd)

      type(context_t), pointer, intent(in) :: cx
      type(osc_par_t), intent(in)          :: os_p
      type(static_ibound_t)                :: bd

      class(model_t), pointer :: ml
      type(point_t)           :: pt

      ! Construct the static_ibound_t

      ml => cx%model()
      pt = cx%point_i()

      select case (os_p%inner_bound)
      case ('REGULAR')
         @:ASSERT(pt%x == 0._RD, 'boundary condition invalid for x /= 0')
         bd%eval_ => eval_regular_
      case default
         @:ABORT('invalid inner_bound')
      end select

      bd%cx => cx

      ! Other initializations

      bd%n_e = 1
      bd%n_v = 2

      ! Finish

      return

   end function static_ibound_t_

   !****

   subroutine eval(this, st, E, scl, F, trans)

      class(static_ibound_t), intent(in)          :: this
      class(state_rt), intent(in)                 :: st
      real(RD), contiguous, intent(out)           :: E(:,:)
      type(ext_rt), intent(out)                   :: scl
      real(RD), contiguous, intent(out), optional :: F(:)
      logical, intent(in), optional               :: trans

      ! Evaluate the inner boundary condition matrix and inhomogeneous
      ! vector

      call this%eval_(st, E, F, trans)

      scl = ONE_rt

      ! Finish

      return

   end subroutine eval

   !****

   subroutine eval_regular_(this, st, B, F, trans)

      class(static_ibound_t), intent(in)          :: this
      class(state_rt), intent(in)                 :: st
      real(RD), contiguous, intent(out)           :: B(:,:)
      real(RD), contiguous, intent(out), optional :: F(:)
      logical, intent(in), optional               :: trans

      logical :: trans_

      if (PRESENT(trans)) then
         trans_ = trans
      else
         trans_ = .FALSE.
      end if

      if (trans_) then
         @:CHECK_BOUNDS(SIZE(B, 1), this%n_v)
         @:CHECK_BOUNDS(SIZE(B, 2), this%n_e)
      else
         @:CHECK_BOUNDS(SIZE(B, 1), this%n_e)
         @:CHECK_BOUNDS(SIZE(B, 2), this%n_v)
      end if

      if (PRESENT(F)) then
         @:CHECK_BOUNDS(SIZE(F), this%n_e)
      end if

      ! Evaluate the inner boundary condition matrix and inhomogeneous
      ! vector (regularity-enforcing)

      associate (&
         l_e => this%cx%l)

         #:include 'IB_regular.inc'

      end associate

      ! Finish

      return

   end subroutine eval_regular_

end module static_ibound_m
