! Module  : static_bvp_m
! Purpose : static-tide bounary value problem solver
!
! Copyright 2013-2026 Rich Townsend & The GYRE Team
!
! This file is part of GYRE. GYRE is free software: you can
! redistribute it and/or modify it under the terms of the GNU General
! Public License as published by the Free Software Foundation, version 3.
!
! GYRE is distributed in the hope that it will be useful, but WITHOUT
! ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
! or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
! License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.

#:include 'gyre.inc'

module static_bvp_m

   ! Uses

   use forum_m, only: RD

   use bvp_m
   use context_m
   use grid_m
   use model_m
   use mode_par_m
   use num_par_m
   use orbit_par_m
   use osc_par_m
   use point_m
   use resp_m
   use state_m
   use sysmtx_m
   use wave_m

   use ISO_FORTRAN_ENV

   ! No implicit typing

   implicit none (type, external)

   ! Derived-type definitions

   type, extends(bvp_rt) :: static_bvp_t
      private
      type(context_t), pointer :: cx => null()
      type(grid_t)             :: gr
      type(mode_par_t)         :: md_p
      type(num_par_t)          :: nm_p
      type(osc_par_t)          :: os_p
   end type static_bvp_t

   ! Interfaces

   interface static_bvp_t
      module procedure static_bvp_t_
   end interface static_bvp_t

   interface resp_t
      module procedure resp_t_
   end interface resp_t

   ! Access specifiers

   public :: static_bvp_t
   public :: resp_t

   ! Default access

   private

contains

   function static_bvp_t_(cx, gr, md_p, nm_p, os_p) result(bp)

      use bound_conds_m
      use static_ibound_conds_m
      use static_obound_conds_m

      type(context_t), pointer, intent(in) :: cx
      type(grid_t), intent(in)             :: gr
      type(mode_par_t), intent(in)         :: md_p
      type(num_par_t), intent(in)          :: nm_p
      type(osc_par_t), intent(in)          :: os_p
      type(static_bvp_t)                   :: bp

      class(bound_conds_rt), allocatable :: bc_i
      class(bound_conds_rt), allocatable :: bc_o

      ! Construct the static_bvp type

      ! Initialize the base type

      bc_i = static_ibound_conds_t(cx, os_p)
      bc_o = static_obound_conds_t(cx, os_p)

      bp%bvp_rt = bvp_rt(gr, bc_i, bc_o, diff_eqns_factory_, match_conds_factory_, nm_p)

      ! Other initializations

      bp%cx => cx
      bp%gr = gr

      bp%md_p = md_p
      bp%nm_p = nm_p
      bp%os_p = os_p

      ! Finish

      return

   contains

      subroutine diff_eqns_factory_(pt, de)

         use diff_eqns_m
         use static_diff_eqns_m

         type(point_t), intent(in)                     :: pt(:)
         class(diff_eqns_rt), allocatable, intent(out) :: de(:)

         ! Initialize the differential equations

         #:if defined('GFORTRAN_PR125610')
         de = static_diff_eqns_t_1_(cx, pt)
         #:else
         de = static_diff_eqns_t(cx, pt)
         #:endif

         ! Finish

         return

      end subroutine diff_eqns_factory_

      !****

      subroutine match_conds_factory_(pt, mc)

         use match_conds_m
         use static_match_conds_m

         type(point_t), intent(in)                       :: pt(:)
         class(match_conds_rt), allocatable, intent(out) :: mc(:)

         ! Initialize the match conditions

         #:if defined('GFORTRAN_PR125610')
         mc = static_match_conds_t_1_(cx, pt)
         #:else
         mc = static_match_conds_t(cx, pt)
         #:endif

         ! Finish

         return

      end subroutine match_conds_factory_

   end function static_bvp_t_

   !****

   function resp_t_(bp, sm, st, id, or_p, k) result(rs)

      class(static_bvp_t), intent(in) :: bp
      class(sysmtx_rt), intent(inout) :: sm
      type(state_rt), intent(in)      :: st
      integer, intent(in)             :: id
      type(orbit_par_t), intent(in)   :: or_p
      integer, intent(in)             :: k
      type(resp_t)                    :: rs

      real(RD)                :: y(2,bp%n)
      type(state_ct)          :: st_c
      class(model_t), pointer :: ml
      integer                 :: j
      real(RD)                :: U
      real(RD)                :: c_1
      complex(RD)             :: lambda
      complex(RD)             :: y_c(6,bp%n)
      complex(RD)             :: y_h(bp%n)
      type(wave_t)            :: wv

      ! Calculate the inhomogeneous solution vector

      call bp%solve_inhom(sm, st, y)

      ! Convert to canonical form

      st_c = state_ct(CMPLX(st%omega, KIND=RD), st%omega, y_T_1=st%y_T_1)

      ml => bp%cx%model()

      !$OMP PARALLEL DO PRIVATE (U, c_1, lambda)
      do j = 1, bp%n

         associate( &
            y_T_1 => st%y_T_1, &
            pt => bp%gr%pt(j), &
            alpha_grv => bp%cx%alpha_grv, &
            l_e => bp%cx%l)

            U = ml%coeff(I_U, pt)
            c_1 = ml%coeff(I_C_1, pt)

            lambda = l_e*(l_e+1._RD)

            y_c(1,j) = -(alpha_grv*y(1,j) + c_1*y_T_1)
            y_c(2,j) = y_c(1,j)
            y_c(3,j) = y(1,j)
            y_c(4,j) = y(2,j)
            y_c(5,j) = 0._RD
            y_c(6,j) = 0._RD

            ! Evaluate y_h from the continuity equation because the
            ! the horizontal momentum equation can't be used when
            ! sigma=0

            y_h(j) = -(alpha_grv*((4._RD - U)*y_c(3,j) + y_c(4,j)) + (4._RD - U + l_e)*c_1*y_T_1)/lambda

         end associate

      end do

      ! Construct the wave_t

      wv = wave_t(st_c, y_c, bp%cx, bp%gr, bp%md_p, bp%nm_p, bp%os_p, id, 0._RD, 1)

      rs = resp_t(wv, or_p, k, y_h=y_h)

      ! Finish

      return

   end function resp_t_

end module static_bvp_m
