! Module  : static_diff_eqns_m
! Purpose : static-tide differential equations evaluation
!
! Copyright 2013-2026 Rich Townsend & The GYRE Team
!
! This file is part of GYRE. GYRE is free software: you can
! redistribute it and/or modify it under the terms of the GNU General
! Public License as published by the Free Software Foundation, version 3.
!
! GYRE is distributed in the hope that it will be useful, but WITHOUT
! ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
! or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
! License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.

#:include 'gyre.inc'

module static_diff_eqns_m

   ! Uses

   use forum_m, only: RD

   use context_m
   use diff_eqns_m
   use model_m
   use model_util_m
   use point_m
   use state_m

   use ISO_FORTRAN_ENV

   ! No implicit typing

   implicit none (type, external)

   ! Derived-type definitions

   type, extends(diff_eqns_rt) :: static_diff_eqns_t
      private
      type(context_t), pointer :: cx => null()
      real(RD)                 :: V_g
      real(RD)                 :: As
      real(RD)                 :: U
      real(RD)                 :: c_1
      real(RD)                 :: x
   contains
      private
      procedure, public :: eval
   end type static_diff_eqns_t

   ! Interfaces

   interface static_diff_eqns_t
      module procedure static_diff_eqns_t_0_
      module procedure static_diff_eqns_t_1_
   end interface static_diff_eqns_t

   ! Access specifiers

   public :: static_diff_eqns_t
   public :: static_diff_eqns_t_0_
   public :: static_diff_eqns_t_1_

   ! Default access

   private

contains

   function static_diff_eqns_t_0_(cx, pt) result(de)

      class(context_t), pointer, intent(in) :: cx
      type(point_t), intent(in)             :: pt
      type(static_diff_eqns_t)              :: de

      class(model_t), pointer :: ml

      ! Construct the static_diff_eqns type

      de%cx => cx

      ! Store structure coefficients

      ml => cx%model()

      call check_model(ml, [I_V_2,I_AS,I_U,I_C_1,I_GAMMA_1])

      @:ASSERT(.NOT. ml%is_vacuum(pt), 'vacuum point')

      de%V_g = ml%coeff(I_V_2, pt)*pt%x**2/ml%coeff(I_GAMMA_1, pt)
      de%As = ml%coeff(I_AS, pt)
      de%U = ml%coeff(I_U, pt)
      de%c_1 = ml%coeff(I_C_1, pt)

      ! Other initializations

      de%x = pt%x

      de%n_e = 2

      ! Finish

      return

   end function static_diff_eqns_t_0_

   !****

   function static_diff_eqns_t_1_(cx, pt) result(de)

      type(context_t), pointer, intent(in) :: cx
      type(point_t), intent(in)            :: pt(:)
      type(static_diff_eqns_t)             :: de(SIZE(pt))

      integer :: j

      ! Construct the array of static_diff_eqns types

      do j = 1, SIZE(pt)
         de(j) = static_diff_eqns_t(cx, pt(j))
      end do

      ! Finish

      return

   end function static_diff_eqns_t_1_

   !****

   subroutine eval(this, st, del, A, r, trans)

      class(static_diff_eqns_t), intent(in) :: this
      class(state_rt), intent(in)           :: st
      real(RD), intent(in)                  :: del
      real(RD), intent(out)                 :: A(:,:)
      real(RD), intent(out), optional       :: r(:)
      logical, intent(in), optional         :: trans

      logical  :: trans_
      real(RD) :: lambda
      real(RD) :: del_x

      if (PRESENT(trans)) then
         trans_ = trans
      else
         trans_ = .FALSE.
      end if

      @:CHECK_BOUNDS(SIZE(A, 1), this%n_e)
      @:CHECK_BOUNDS(SIZE(A, 2), this%n_e)

      if (PRESENT(r)) then
         @:CHECK_BOUNDS(SIZE(r), this%n_e)
      end if

      ! Evaluate the Jacobian matrix and inhomogeneous vector

      associate ( &
         y_T_1 => st%y_T_1, &
         V_g => this%V_g, &
         As => this%As, &
         U => this%U, &
         c_1 => this%c_1, &
         x => this%x, &
         l_e => this%cx%l)

         lambda = l_e*(l_e+1._RD)

         del_x = del/x

         #:include 'A.inc'

      end associate

      ! Finish

      return

   end subroutine eval

end module static_diff_eqns_m
