! Module  : static_match_conds_m
! Purpose : static-tide match conditions evaluation
!
! Copyright 2013-2026 Rich Townsend & The GYRE Team
!
! This file is part of GYRE. GYRE is free software: you can
! redistribute it and/or modify it under the terms of the GNU General
! Public License as published by the Free Software Foundation, version 3.
!
! GYRE is distributed in the hope that it will be useful, but WITHOUT
! ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
! or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
! License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.

#:include 'gyre.inc'

module static_match_conds_m

   ! Uses

   use forum_m, only: RD

   use context_m
   use match_conds_m
   use model_m
   use model_util_m
   use point_m
   use state_m

   use ISO_FORTRAN_ENV

   ! No implicit typing

   implicit none (type, external)

   ! Derived-type definitions

   type, extends(match_conds_rt) :: static_match_conds_t
      private
      type(context_t), pointer :: cx => null()
      real(RD)                 :: U
   contains
      private
      procedure, public :: eval
   end type static_match_conds_t

   ! Interfaces

   interface static_match_conds_t
      module procedure static_match_conds_t_0_
      module procedure static_match_conds_t_1_
   end interface static_match_conds_t

   ! Access specifiers

   public :: static_match_conds_t
   public :: static_match_conds_t_0_
   public :: static_match_conds_t_1_

   ! Default access

   private

contains

   function static_match_conds_t_0_(cx, pt) result(mc)

      class(context_t), pointer, intent(in) :: cx
      type(point_t), intent(in)             :: pt
      type(static_match_conds_t)            :: mc

      class(model_t), pointer :: ml

      ! Construct the static_match_conds type

      mc%cx => cx

      ! Store structure coefficients

      ml => cx%model()

      call check_model(ml, [I_U])

      @:ASSERT(.NOT. ml%is_vacuum(pt), 'vacuum point')

      mc%U = ml%coeff(I_U, pt)

      ! Other initializations

      mc%n_e = 2

      ! Finish

      return

   end function static_match_conds_t_0_

   !****

   function static_match_conds_t_1_(cx, pt) result(mc)

      type(context_t), pointer, intent(in) :: cx
      type(point_t), intent(in)            :: pt(:)
      type(static_match_conds_t)           :: mc(SIZE(pt))

      integer :: j

      ! Construct the array of static_match_conds types

      do j = 1, SIZE(pt)
         mc(j) = static_match_conds_t(cx, pt(j))
      end do

      ! Finish

      return

   end function static_match_conds_t_1_

   !****

   subroutine eval(this, st, C, t, trans)

      class(static_match_conds_t), intent(in) :: this
      class(state_rt), intent(in)             :: st
      real(RD), intent(out)                   :: C(:,:)
      real(RD), intent(out), optional         :: t(:)
      logical, intent(in), optional           :: trans

      logical :: trans_

      if (PRESENT(trans)) then
         trans_ = trans
      else
         trans_ = .FALSE.
      end if

      @:CHECK_BOUNDS(SIZE(C, 1), this%n_e)
      @:CHECK_BOUNDS(SIZE(C, 2), this%n_e)

      if (PRESENT(t)) then
         @:CHECK_BOUNDS(SIZE(t), this%n_e)
      end if

      ! Evaluate the match matrix and inhomogeneous vector

      associate ( &
         U => this%U)

         #:include 'C.inc'

      end associate

      ! Finish

      return

   end subroutine eval

end module static_match_conds_m
