# File     : Makefile
# Purpose  : makefile for src/trad subdir

# Variables

TARGETS=build_tar_fit

# Flags

HDF5=yes
FPE=no

LDFLAGS=`mesasdk_hdf5_link`

# Include other makefiles

SUBDIRS=../extern/core:../common

include ../build/Make.inc

