! Module  : rad_factory_m
! Purpose : factory methods for radial adiabatic routines
!
! Copyright 2013-2026 Rich Townsend & The GYRE Team
!
! This file is part of GYRE. GYRE is free software: you can
! redistribute it and/or modify it under the terms of the GNU General
! Public License as published by the Free Software Foundation, version 3.
!
! GYRE is distributed in the hope that it will be useful, but WITHOUT
! ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
! or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
! License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.

#:include 'gyre.inc'

module rad_factory_m

   ! Uses

   use forum_m, only: RD

   use context_m
   use osc_par_m
   use point_m

   use ISO_FORTRAN_ENV

   ! No implicit typing

   implicit none (type, external)

   ! Interfaces

   interface rad_diff_eqns_t
      module procedure rad_diff_eqns_t_0_
      module procedure rad_diff_eqns_t_1_
   end interface rad_diff_eqns_t

   interface rad_match_conds_t
      module procedure rad_match_conds_t_0_
      module procedure rad_match_conds_t_1_
   end interface rad_match_conds_t

   interface rad_trans_t
      module procedure rad_trans_t_0_
      module procedure rad_trans_t_1_
   end interface rad_trans_t

   ! Access specifiers

   public :: rad_diff_eqns_t
   public :: rad_match_conds_t
   public :: rad_trans_t
   public :: rad_ibound_conds_t
   public :: rad_obound_conds_t
   #:if defined('GFORTRAN_PR125610')
   public :: rad_diff_eqns_t_0_
   public :: rad_diff_eqns_t_1_
   public :: rad_match_conds_t_0_
   public :: rad_match_conds_t_1_
   public :: rad_trans_t_0_
   public :: rad_trans_t_1_
   #:endif

   ! Default access

   private

contains

   #:for R in (0, 1)

      function rad_diff_eqns_t_${R}$_(cx, pt, os_p) result(de)

         use diff_eqns_m

         use gyre_rad_diff_eqns_m
         use dziem_rad_diff_eqns_m
         use jcd_rad_diff_eqns_m
         use mix_rad_diff_eqns_m
         use lagp_rad_diff_eqns_m

         type(context_t), pointer, intent(in) :: cx
         type(point_t), intent(in)            :: pt${ARRAY_SPEC(R)}$
         type(osc_par_t), intent(in)          :: os_p
         class(diff_eqns_rt), allocatable     :: de${ARRAY_SPEC(R)}$

         ! Construct the rad_diff_eqns type

         select case(os_p%variables_set)
         case('GYRE')
            de = gyre_rad_diff_eqns_t(cx, pt)
         case('DZIEM')
            de = dziem_rad_diff_eqns_t(cx, pt)
         case('JCD')
            de = jcd_rad_diff_eqns_t(cx, pt)
         case('MIX')
            de = mix_rad_diff_eqns_t(cx, pt)
         case('LAGP')
            de = lagp_rad_diff_eqns_t(cx, pt)
         case default
            @:ABORT('invalid variables_set')
         end select

         ! Finish

         return

      end function rad_diff_eqns_t_${R}$_

      !****

      function rad_match_conds_t_${R}$_(cx, pt, os_p) result(mc)

         use match_conds_m

         use gyre_rad_match_conds_m
         use dziem_rad_match_conds_m
         use jcd_rad_match_conds_m
         use mix_rad_match_conds_m
         use lagp_rad_match_conds_m

         type(context_t), pointer, intent(in) :: cx
         type(point_t), intent(in)            :: pt${ARRAY_SPEC(R)}$
         type(osc_par_t), intent(in)          :: os_p
         class(match_conds_rt), allocatable   :: mc${ARRAY_SPEC(R)}$

         ! Construct the rad_match_conds

         select case(os_p%variables_set)
         case('GYRE')
            mc = gyre_rad_match_conds_t(cx, pt)
         case('DZIEM')
            mc = dziem_rad_match_conds_t(cx, pt)
         case('JCD')
            mc = jcd_rad_match_conds_t(cx, pt)
         case('MIX')
            mc = mix_rad_match_conds_t(cx, pt)
         case('LAGP')
            mc = lagp_rad_match_conds_t(cx, pt)
         case default
            @:ABORT('invalid variables_set')
         end select

         ! Finish

         return

      end function rad_match_conds_t_${R}$_

      !****

      function rad_trans_t_${R}$_(cx, pt, os_p) result(tr)

         use trans_m

         use gyre_rad_trans_m
         use dziem_rad_trans_m
         use jcd_rad_trans_m
         use mix_rad_trans_m
         use lagp_rad_trans_m

         type(context_t), pointer, intent(in) :: cx
         type(point_t), intent(in)            :: pt${ARRAY_SPEC(R)}$
         type(osc_par_t), intent(in)          :: os_p
         class(trans_rt), allocatable         :: tr${ARRAY_SPEC(R)}$

         ! Construct the rad_trans type

         select case(os_p%variables_set)
         case('GYRE')
            tr = gyre_rad_trans_t(cx, pt)
         case('DZIEM')
            tr = dziem_rad_trans_t(cx, pt)
         case('JCD')
            tr = jcd_rad_trans_t(cx, pt)
         case('MIX')
            tr = mix_rad_trans_t(cx, pt)
         case('LAGP')
            tr = lagp_rad_trans_t(cx, pt)
         case default
            @:ABORT('invalid variables_set')
         end select

         ! Finish

         return

      end function rad_trans_t_${R}$_

   #:endfor

   !****

   function rad_ibound_conds_t(cx, os_p) result(bc)

      use bound_conds_m

      use gyre_rad_ibound_conds_m
      use dziem_rad_ibound_conds_m
      use jcd_rad_ibound_conds_m
      use mix_rad_ibound_conds_m
      use lagp_rad_ibound_conds_m

      type(context_t), pointer, intent(in) :: cx
      type(osc_par_t), intent(in)          :: os_p
      class(bound_conds_rt), allocatable   :: bc

      ! Construct the rad_ibound_conds type

      select case(os_p%variables_set)
      case('GYRE')
         bc = gyre_rad_ibound_conds_t(cx, os_p)
      case('DZIEM')
         bc = dziem_rad_ibound_conds_t(cx, os_p)
      case('JCD')
         bc = jcd_rad_ibound_conds_t(cx, os_p)
      case('MIX')
         bc = mix_rad_ibound_conds_t(cx, os_p)
      case('LAGP')
         bc = lagp_rad_ibound_conds_t(cx, os_p)
      case default
         @:ABORT('invalid variables_set')
      end select

      ! Finish

      return

   end function rad_ibound_conds_t

   !****

   function rad_obound_conds_t(cx, os_p) result(bc)

      use bound_conds_m

      use gyre_rad_obound_conds_m
      use dziem_rad_obound_conds_m
      use jcd_rad_obound_conds_m
      use mix_rad_obound_conds_m
      use lagp_rad_obound_conds_m

      type(context_t), pointer, intent(in) :: cx
      type(osc_par_t), intent(in)          :: os_p
      class(bound_conds_rt), allocatable   :: bc

      ! Construct the rad_obound_conds type

      select case(os_p%variables_set)
      case('GYRE')
         bc = gyre_rad_obound_conds_t(cx, os_p)
      case('DZIEM')
         bc = dziem_rad_obound_conds_t(cx, os_p)
      case('JCD')
         bc = jcd_rad_obound_conds_t(cx, os_p)
      case('MIX')
         bc = mix_rad_obound_conds_t(cx, os_p)
      case('LAGP')
         bc = lagp_rad_obound_conds_t(cx, os_p)
      case default
         @:ABORT('invalid variables_set')
      end select

      ! Finish

      return

   end function rad_obound_conds_t

end module rad_factory_m
