# File     : Makefile
# Purpose  : makefile for src/wave subdir

# Variables

TARGETS=build_trad_table test_trad_table

# Flags

HDF5=yes

LDFLAGS=`mesasdk_hdf5_link`

# Include other makefiles

SUBDIRS=../extern/core:../extern/astro:../common

include ../Make.inc
