! Module  : bvp_m
! Purpose : parametric boundary value problems
!
! Copyright 2013-2026 Rich Townsend & The GYRE Team
!
! This file is part of GYRE. GYRE is free software: you can
! redistribute it and/or modify it under the terms of the GNU General
! Public License as published by the Free Software Foundation, version 3.
!
! GYRE is distributed in the hope that it will be useful, but WITHOUT
! ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
! or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
! License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.

#:include 'gyre.inc'

module bvp_m

   ! Uses

   use forum_m, only: RD

   use bound_block_m
   use bound_conds_m
   use diff_block_factory_m
   use ext_m
   use grid_m
   use inter_element_m
   use inter_block_m
   use match_block_m
   use num_par_m
   use state_m
   use status_m
   use sysmtx_m

   use ISO_FORTRAN_ENV

   ! No implicit typing

   implicit none (type, external)

   #:for T, S in zip(DTYPE_BASE_TYPES, DTYPE_SUFFIXES)

      ! Derived-type definitions

      type :: bvp_${S}$
         private
         class(bound_block_${S}$), allocatable   :: bb_i
         class(bound_block_${S}$), allocatable   :: bb_o
         class(inter_element_${S}$), allocatable :: ie(:)
         integer, public                         :: n
         integer, public                         :: n_e
         integer, public                         :: n_i
         integer, public                         :: n_o
      contains
         private
         procedure, public :: eval_det => eval_det_${S}$_
         procedure, public :: solve_hom => solve_hom_${S}$_
         procedure, public :: solve_inhom => solve_inhom_${S}$_
      end type bvp_${S}$

      ! Interfaces

      interface bvp_${S}$
         module procedure bvp_${S}$_
      end interface bvp_${S}$

      ! Access specifiers

      public :: bvp_${S}$

   #:endfor

   ! Default access

   private

contains

   #:for T, S in zip(DTYPE_BASE_TYPES, DTYPE_SUFFIXES)

      function bvp_${S}$_(gr, bc_i, bc_o, diff_eqns_factory, match_conds_factory, nm_p) result(bp)

         type(grid_t), intent(in)             :: gr
         class(bound_conds_${S}$), intent(in) :: bc_i
         class(bound_conds_${S}$), intent(in) :: bc_o
         interface
            subroutine diff_eqns_factory(pt, de)
               use diff_eqns_m
               use point_m
               type(point_t), intent(in)                        :: pt(:)
               class(diff_eqns_${S}$), allocatable, intent(out) :: de(:)
            end subroutine diff_eqns_factory
            subroutine match_conds_factory(pt, mc)
               use match_conds_m
               use point_m
               type(point_t), intent(in)                          :: pt(:)
               class(match_conds_${S}$), allocatable, intent(out) :: mc(:)
            end subroutine match_conds_factory
         end interface
         type(num_par_t), intent(in) :: nm_p
         type(bvp_${S}$)             :: bp

         integer :: n
         integer :: n_e
         integer :: n_i
         integer :: n_o
         integer :: j

         ! Perform basic dimension validations

         n = gr%n

         n_e = bc_i%n_e
         @:CHECK_BOUNDS(bc_o%n_e, n_e)

         n_i = bc_i%n_b
         n_o = bc_o%n_b

         @:CHECK_BOUNDS(n_i+n_o, n_e)

         ! Set up blocks

         bp%bb_i = bound_block_${S}$(bc_i)
         bp%bb_o = bound_block_${S}$(bc_o)

         allocate(bp%ie(n-1))

         !$OMP PARALLEL DO
         do j = 1, n-1

            associate( &
               pt_a => gr%pt(j), &
               pt_b => gr%pt(j+1))

               if (pt_a%s == pt_b%s) then
                  allocate(bp%ie(j)%ib, SOURCE=diff_block_${S}$(diff_eqns_factory, pt_a, pt_b, nm_p))
               else
                  allocate(bp%ie(j)%ib, SOURCE=match_block_${S}$(match_conds_factory, pt_a, pt_b))
               end if

               @:CHECK_BOUNDS(bp%ie(j)%ib%n_e, n_e)

            end associate

         end do

         ! Other initializations

         bp%n = n
         bp%n_e = n_e
         bp%n_i = n_i
         bp%n_o = n_o

         ! Finish

         return

      end function bvp_${S}$_

      !****

      subroutine eval_det_${S}$_(this, sm, st, det)

         class(bvp_${S}$), intent(in)       :: this
         class(sysmtx_${S}$), intent(inout) :: sm
         class(state_${S}$), intent(in)     :: st
         type(ext_${S}$), intent(out)       :: det

         @:ASSERT_DEBUG(sm%n+1 == this%n, 'dimension mismatch')
         @:ASSERT_DEBUG(sm%n_e == this%n_e, 'dimension mismatch')
         @:ASSERT_DEBUG(sm%n_i == this%n_i, 'dimension mismatch')
         @:ASSERT_DEBUG(sm%n_o == this%n_o, 'dimension mismatch')

         ! Evaluate the determinant of the sysmtx

         call sm%eval_det(st, this%bb_i, this%bb_o, this%ie, det)

         ! Finish

         return

      end subroutine eval_det_${S}$_

      !****

      subroutine solve_hom_${S}$_(this, sm, st, y)

         class(bvp_${S}$), intent(in)       :: this
         class(sysmtx_${S}$), intent(inout) :: sm
         class(state_${S}$), intent(in)     :: st
         ${T}$, intent(out)                 :: y(:,:)

         ${T}$ :: u(this%n_e*this%n)

         @:ASSERT_DEBUG(sm%n+1 == this%n, 'dimension mismatch')
         @:ASSERT_DEBUG(sm%n_e == this%n_e, 'dimension mismatch')
         @:ASSERT_DEBUG(sm%n_i == this%n_i, 'dimension mismatch')
         @:ASSERT_DEBUG(sm%n_o == this%n_o, 'dimension mismatch')

         @:CHECK_BOUNDS(SIZE(y, 1), this%n_e)
         @:CHECK_BOUNDS(SIZE(y, 2), this%n)

         ! Evaluate the solution vector y of the homogeneous system

         call sm%solve_hom(st, this%bb_i, this%bb_o, this%ie, u)

         y = RESHAPE(u, SHAPE(y))

         ! Finish

         return

      end subroutine solve_hom_${S}$_

      !****

      subroutine solve_inhom_${S}$_(this, sm, st, y)

         class(bvp_${S}$), intent(in)       :: this
         class(sysmtx_${S}$), intent(inout) :: sm
         class(state_${S}$), intent(in)     :: st
         ${T}$, intent(out)                 :: y(:,:)

         ${T}$ :: u(this%n_e*this%n)

         @:ASSERT_DEBUG(sm%n+1 == this%n, 'dimension mismatch')
         @:ASSERT_DEBUG(sm%n_e == this%n_e, 'dimension mismatch')
         @:ASSERT_DEBUG(sm%n_i == this%n_i, 'dimension mismatch')
         @:ASSERT_DEBUG(sm%n_o == this%n_o, 'dimension mismatch')

         @:CHECK_BOUNDS(SIZE(y, 1), this%n_e)
         @:CHECK_BOUNDS(SIZE(y, 2), this%n)

         ! Evaluate the solution vector y of the inhomogeneous system

         call sm%solve_inhom(st, this%bb_i, this%bb_o, this%ie, u)

         y = RESHAPE(u, SHAPE(y))

         ! Finish

         return

      end subroutine solve_inhom_${S}$_

   #:endfor

end module bvp_m
